export interface Puzzle {
  id: string;
  title: string;
  fen: string;
  solution: string[]; // UCI moves e.g. "e2e4"
  rating: number;     // Lichess-style puzzle rating
  hint: string;
  explanation: string;
}

const puzzles: Puzzle[] = [

  // ── BEGINNER (rating 200-600) — mate in 1 ─────────────────────────────────
  {
    id: 'b001',
    title: 'Back Rank Rook Mate 1',
    fen: '6k1/5ppp/8/8/8/8/8/R6K w - - 0 1',
    solution: ["a1a8"],
    rating: 200,
    hint: 'Slide the rook all the way to the 8th rank!',
    explanation: 'Ra8# — the rook delivers checkmate. The king on g8 is trapped by its own f7, g7, h7 pawns.',
  },
  {
    id: 'b002',
    title: 'Back Rank Rook Mate 2',
    fen: '6k1/5ppp/8/8/8/8/8/1R5K w - - 0 1',
    solution: ["b1b8"],
    rating: 204,
    hint: 'Slide the rook up the open b-file!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. The pawns f7, g7, h7 trap the king in the corner.',
  },
  {
    id: 'b003',
    title: 'Back Rank Rook Mate 3',
    fen: '6k1/5ppp/8/8/8/8/8/2R4K w - - 0 1',
    solution: ["c1c8"],
    rating: 208,
    hint: 'Fire the rook up the c-file!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The three pawns seal the king\'s fate.',
  },
  {
    id: 'b004',
    title: 'Back Rank Rook Mate 4',
    fen: '6k1/5ppp/8/8/8/8/8/3R3K w - - 0 1',
    solution: ["d1d8"],
    rating: 212,
    hint: 'Aim the rook at the 8th rank along the d-file!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. The king on g8 cannot escape past its own pawns.',
  },
  {
    id: 'b005',
    title: 'Back Rank Rook Mate 5',
    fen: '6k1/5ppp/8/8/8/8/8/4R2K w - - 0 1',
    solution: ["e1e8"],
    rating: 216,
    hint: 'The e-file leads straight to checkmate!',
    explanation: 'Re8# — the rook races to e8, delivering checkmate. Three pawns trap the king completely.',
  },
  {
    id: 'b006',
    title: 'Back Rank Rook Mate 6',
    fen: '6k1/4pppp/8/8/8/8/8/R6K w - - 0 1',
    solution: ["a1a8"],
    rating: 220,
    hint: 'Four pawns trap the king — use the open a-file!',
    explanation: 'Ra8# — the rook blasts up the a-file. Four pawns on e7-h7 box in the king completely.',
  },
  {
    id: 'b007',
    title: 'Back Rank Rook Mate 7',
    fen: '6k1/4pppp/8/8/8/8/8/1R5K w - - 0 1',
    solution: ["b1b8"],
    rating: 224,
    hint: 'The b-file leads to the trapped king!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Four pawns completely seal the Black king.',
  },
  {
    id: 'b008',
    title: 'Back Rank Rook Mate 8',
    fen: '6k1/4pppp/8/8/8/8/8/2R4K w - - 0 1',
    solution: ["c1c8"],
    rating: 228,
    hint: 'Use the c-file for checkmate!',
    explanation: 'Rc8# — the rook delivers checkmate. The four pawns trap the king with no escape.',
  },
  {
    id: 'b009',
    title: 'Back Rank Rook Mate 9',
    fen: '6k1/4pppp/8/8/8/8/8/3R3K w - - 0 1',
    solution: ["d1d8"],
    rating: 232,
    hint: 'Send the d-rook to the 8th rank!',
    explanation: 'Rd8# — the rook delivers checkmate. Four pawns completely block the king\'s escape.',
  },
  {
    id: 'b010',
    title: 'Corner King Rook Mate 1',
    fen: '7k/6pp/8/8/8/8/8/R6K w - - 0 1',
    solution: ["a1a8"],
    rating: 236,
    hint: 'The rook can zoom to the 8th rank in one move!',
    explanation: 'Ra8# — the rook races to a8. The king on h8 is trapped by g7 and h7 pawns.',
  },
  {
    id: 'b011',
    title: 'Corner King Rook Mate 2',
    fen: '7k/6pp/8/8/8/8/8/1R5K w - - 0 1',
    solution: ["b1b8"],
    rating: 240,
    hint: 'Use the b-file to deliver checkmate!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. The king on h8 is trapped by its own g7 and h7 pawns.',
  },
  {
    id: 'b012',
    title: 'Corner King Rook Mate 3',
    fen: '7k/6pp/8/8/8/8/8/2R4K w - - 0 1',
    solution: ["c1c8"],
    rating: 244,
    hint: 'Race the rook to the c-file!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The king on h8 cannot escape.',
  },
  {
    id: 'b013',
    title: 'Corner King Rook Mate 4',
    fen: '7k/6pp/8/8/8/8/8/3R3K w - - 0 1',
    solution: ["d1d8"],
    rating: 248,
    hint: 'The d-file strikes at the corner king!',
    explanation: 'Rd8# — the rook on d1 delivers checkmate on d8. Two pawns trap the king on h8.',
  },
  {
    id: 'b014',
    title: 'Corner King Rook Mate 5',
    fen: '7k/6pp/8/8/8/8/8/4R2K w - - 0 1',
    solution: ["e1e8"],
    rating: 252,
    hint: 'The e-file reaches the corner king!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on h8 is trapped by g7 and h7 pawns.',
  },
  {
    id: 'b015',
    title: 'Corner King Rook Mate 6',
    fen: '7k/6pp/8/8/8/8/8/5R1K w - - 0 1',
    solution: ["f1f8"],
    rating: 256,
    hint: 'Swing the rook to the f-file!',
    explanation: 'Rf8# — the rook delivers checkmate on f8. The king on h8 is trapped by its own g7 and h7 pawns.',
  },
  {
    id: 'b016',
    title: 'Corner King Rook Mate 7',
    fen: '7k/5ppp/8/8/8/8/8/R6K w - - 0 1',
    solution: ["a1a8"],
    rating: 260,
    hint: 'Three pawns and a rook — find checkmate!',
    explanation: 'Ra8# — the rook races to a8. Three pawns seal the king\'s fate on h8.',
  },
  {
    id: 'b017',
    title: 'Corner King Rook Mate 8',
    fen: '7k/5ppp/8/8/8/8/8/1R5K w - - 0 1',
    solution: ["b1b8"],
    rating: 264,
    hint: 'The b-file strikes at the cornered king!',
    explanation: 'Rb8# — the rook delivers checkmate. Three pawns trap the king on h8.',
  },
  {
    id: 'b018',
    title: 'Corner King Rook Mate 9',
    fen: '7k/5ppp/8/8/8/8/8/2R4K w - - 0 1',
    solution: ["c1c8"],
    rating: 268,
    hint: 'Aim the rook at the cornered king!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The king on h8 is trapped by f7, g7, h7 pawns.',
  },
  {
    id: 'b019',
    title: 'Corner King Rook Mate 10',
    fen: '7k/5ppp/8/8/8/8/8/3R3K w - - 0 1',
    solution: ["d1d8"],
    rating: 272,
    hint: 'Drive the rook to the 8th rank!',
    explanation: 'Rd8# — the rook delivers checkmate. Three pawns trap the king on h8.',
  },
  {
    id: 'b020',
    title: 'Corner King Rook Mate 11',
    fen: '7k/5ppp/8/8/8/8/8/4R2K w - - 0 1',
    solution: ["e1e8"],
    rating: 276,
    hint: 'The e-file is open — strike!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on h8 cannot escape past its own pawns.',
  },
  {
    id: 'b021',
    title: 'Four Pawn Trap Mate 1',
    fen: '5k2/4pppp/8/8/8/8/8/R6K w - - 0 1',
    solution: ["a1a8"],
    rating: 280,
    hint: 'Four pawns trap the king — use the open a-file!',
    explanation: 'Ra8# — the rook blasts to a8. Four pawns e7, f7, g7, h7 completely box in the king on f8.',
  },
  {
    id: 'b022',
    title: 'Four Pawn Trap Mate 2',
    fen: '5k2/4pppp/8/8/8/8/8/1R5K w - - 0 1',
    solution: ["b1b8"],
    rating: 284,
    hint: 'The b-file leads to the trapped king!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Four pawns completely seal the Black king on f8.',
  },
  {
    id: 'b023',
    title: 'Four Pawn Trap Mate 3',
    fen: '5k2/4pppp/8/8/8/8/8/2R4K w - - 0 1',
    solution: ["c1c8"],
    rating: 288,
    hint: 'The c-file reaches the back rank!',
    explanation: 'Rc8# — the rook delivers checkmate. The four pawns seal all escape routes.',
  },
  {
    id: 'b024',
    title: 'Four Pawn Trap Mate 4',
    fen: '5k2/4pppp/8/8/8/8/8/3R3K w - - 0 1',
    solution: ["d1d8"],
    rating: 292,
    hint: 'The d-file strikes the back rank!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. The king on f8 is completely trapped by four pawns.',
  },
  {
    id: 'b025',
    title: 'Five Pawn Cage Mate 1',
    fen: '4k3/3ppppp/8/8/8/8/8/2R4K w - - 0 1',
    solution: ["c1c8"],
    rating: 296,
    hint: 'Five pawns surround the king — deliver checkmate!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. Five pawns from d7 to h7 completely cage the king on e8.',
  },
  {
    id: 'b026',
    title: 'Five Pawn Cage Mate 2',
    fen: '4k3/3ppppp/8/8/8/8/8/1R5K w - - 0 1',
    solution: ["b1b8"],
    rating: 300,
    hint: 'Use the b-file to strike at the caged king!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Five pawns completely trap the king on e8.',
  },
  {
    id: 'b027',
    title: 'King a8 Rook Mate 1',
    fen: 'k7/ppp5/8/8/8/8/8/3R3K w - - 0 1',
    solution: ["d1d8"],
    rating: 304,
    hint: 'The king is in the corner — deliver checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. The king on a8 is boxed in by its own pawns on a7, b7, c7.',
  },
  {
    id: 'b028',
    title: 'King a8 Rook Mate 2',
    fen: 'k7/pp6/8/8/8/8/8/3R3K w - - 0 1',
    solution: ["d1d8"],
    rating: 308,
    hint: 'Two pawns trap the corner king!',
    explanation: 'Rd8# — the rook delivers checkmate. The king on a8 is trapped by pawns on a7 and b7.',
  },
  {
    id: 'b029',
    title: 'King a8 Rook Mate 3',
    fen: 'k7/pp6/8/8/8/8/8/2R4K w - - 0 1',
    solution: ["c1c8"],
    rating: 312,
    hint: 'The c-file reaches the corner king!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The king on a8 is trapped by pawns on a7 and b7.',
  },
  {
    id: 'b030',
    title: 'Two Rooks Ladder Mate 1',
    fen: '3k4/8/3K4/8/8/8/8/RR6 w - - 0 1',
    solution: ["a1a8"],
    rating: 316,
    hint: 'One rook cuts off the king, the other delivers checkmate!',
    explanation: 'Ra8# — with the White king controlling c7, d7, e7 and the rook on b1 covering the b-file, Ra8 delivers checkmate. The two-rook ladder is a classic technique!',
  },
  {
    id: 'b031',
    title: 'Two Rooks Ladder Mate 2',
    fen: '7k/8/7K/8/8/8/8/5RR1 w - - 0 1',
    solution: ["f1f8"],
    rating: 320,
    hint: 'Drive one rook to the 8th rank!',
    explanation: 'Rf8# — the rook delivers checkmate on f8. The rook on g1 covers the g-file and the White king on h6 controls g7, h7, and other key squares.',
  },
  {
    id: 'b032',
    title: 'Two Rooks Ladder Mate 3',
    fen: '7k/8/6K1/8/8/8/8/5RR1 w - - 0 1',
    solution: ["f1f8"],
    rating: 324,
    hint: 'Use the two rooks to corner the king!',
    explanation: 'Rf8# — the rook delivers checkmate on f8. The rook on g1 guards g8, and the White king on g6 controls key squares.',
  },
  {
    id: 'b033',
    title: 'Two Rooks Ladder Mate 4',
    fen: '7k/8/7K/8/8/8/8/4RR2 w - - 0 1',
    solution: ["e1e8"],
    rating: 328,
    hint: 'The e-rook delivers the finishing blow!',
    explanation: 'Re8# — the rook delivers checkmate. The rook on f1 covers the f-file and the White king on h6 controls g7, h7.',
  },
  {
    id: 'b034',
    title: 'Two Rooks Ladder Mate 5',
    fen: '7k/8/7K/8/8/8/8/3RR3 w - - 0 1',
    solution: ["d1d8"],
    rating: 332,
    hint: 'The d-rook strikes at the corner king!',
    explanation: 'Rd8# — the rook delivers checkmate. The rook on e1 covers the e-file and the White king controls key squares on the 7th rank.',
  },
  {
    id: 'b035',
    title: 'Two Rooks with Pawn Cage',
    fen: '6k1/5ppp/8/8/8/8/8/R5RK w - - 0 1',
    solution: ["a1a8"],
    rating: 336,
    hint: 'Use the a-rook to deliver checkmate!',
    explanation: 'Ra8# — the rook on a1 delivers checkmate. The rook on g1 and pawns f7, g7, h7 leave the king with no escape.',
  },
  {
    id: 'b036',
    title: 'Two Rooks Side by Side',
    fen: '6k1/5ppp/8/8/8/8/8/RR5K w - - 0 1',
    solution: ["a1a8"],
    rating: 340,
    hint: 'One rook delivers checkmate, the other backs it up!',
    explanation: 'Ra8# — the rook delivers checkmate on a8. The rook on b1 provides backup control while the pawns seal the king.',
  },
  {
    id: 'b037',
    title: 'Queen Back Rank Mate 1',
    fen: '6k1/5ppp/8/8/8/8/8/Q6K w - - 0 1',
    solution: ["a1a8"],
    rating: 344,
    hint: 'The queen slides to the 8th rank for checkmate!',
    explanation: 'Qa8# — the queen delivers checkmate. The king on g8 is trapped by f7, g7, h7 pawns.',
  },
  {
    id: 'b038',
    title: 'Queen Back Rank Mate 2',
    fen: '6k1/5ppp/8/8/8/8/8/1Q5K w - - 0 1',
    solution: ["b1b8"],
    rating: 348,
    hint: 'The queen strikes on the b-file!',
    explanation: 'Qb8# — the queen delivers checkmate on b8. Three pawns box in the king on g8.',
  },
  {
    id: 'b039',
    title: 'Queen Back Rank Mate 3',
    fen: '6k1/5ppp/8/8/8/8/8/2Q4K w - - 0 1',
    solution: ["c1c8"],
    rating: 352,
    hint: 'Drive the queen up the c-file!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. The three pawns trap the king in the corner.',
  },
  {
    id: 'b040',
    title: 'Queen Back Rank Mate 4',
    fen: '6k1/4pppp/8/8/8/8/8/Q6K w - - 0 1',
    solution: ["a1a8"],
    rating: 356,
    hint: 'Four pawns trap the king — the queen delivers checkmate!',
    explanation: 'Qa8# — the queen sweeps to a8. Four pawns from e7 to h7 completely box in the king.',
  },
  {
    id: 'b041',
    title: 'Queen Back Rank Mate 5',
    fen: '7k/6pp/8/8/8/8/8/Q6K w - - 0 1',
    solution: ["a1a8"],
    rating: 360,
    hint: 'The queen races to the corner for checkmate!',
    explanation: 'Qa8# — the queen delivers checkmate on a8. The king on h8 is trapped by its g7 and h7 pawns.',
  },
  {
    id: 'b042',
    title: 'Queen Back Rank Mate 6',
    fen: '7k/6pp/8/8/8/8/8/1Q5K w - - 0 1',
    solution: ["b1b8"],
    rating: 364,
    hint: 'The b-file strikes at the cornered king!',
    explanation: 'Qb8# — the queen delivers checkmate on b8. The king on h8 is trapped by two pawns.',
  },
  {
    id: 'b043',
    title: 'Queen Back Rank Mate 7',
    fen: '7k/6pp/8/8/8/8/8/2Q4K w - - 0 1',
    solution: ["c1c8"],
    rating: 368,
    hint: 'Aim the queen at the 8th rank!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. The g7 and h7 pawns seal the king\'s fate.',
  },
  {
    id: 'b044',
    title: 'Queen Back Rank Mate 8',
    fen: '6k1/4pppp/8/8/8/8/8/3Q3K w - - 0 1',
    solution: ["d1d8"],
    rating: 372,
    hint: 'Four pawns and the queen — find the checkmate!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Four pawns completely trap the king.',
  },
  {
    id: 'b045',
    title: 'Queen Back Rank Mate 9',
    fen: '7k/6pp/8/8/8/8/8/3Q3K w - - 0 1',
    solution: ["d1d8"],
    rating: 376,
    hint: 'The d-file leads to the corner king!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Two pawns trap the king on h8.',
  },
  {
    id: 'b046',
    title: 'Queen Back Rank Mate 10',
    fen: 'k7/ppp5/8/8/8/8/8/3Q3K w - - 0 1',
    solution: ["d1d8"],
    rating: 380,
    hint: 'The king is in the corner — find the checkmate!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. The king on a8 is boxed in by pawns on a7, b7, c7.',
  },
  {
    id: 'b047',
    title: 'Queen Back Rank Mate 11',
    fen: 'k7/pp6/8/8/8/8/8/3Q3K w - - 0 1',
    solution: ["d1d8"],
    rating: 384,
    hint: 'Two pawns trap the corner king!',
    explanation: 'Qd8# — the queen delivers checkmate. The king on a8 is trapped by pawns on a7 and b7.',
  },
  {
    id: 'b048',
    title: 'Queen Corner Mate 1',
    fen: '7k/5K2/6Q1/8/8/8/8/8 w - - 0 1',
    solution: ["g6g7"],
    rating: 388,
    hint: 'The queen delivers checkmate right beside the king!',
    explanation: 'Qg7# — the queen moves to g7. The king on h8 cannot escape: h7 and g8 are both covered by the queen, and the White king on f7 controls g8 and f8.',
  },
  {
    id: 'b049',
    title: 'Queen Corner Mate 2',
    fen: '8/8/8/8/8/8/1Q6/k1K5 w - - 0 1',
    solution: ["b2b1"],
    rating: 392,
    hint: 'The queen delivers checkmate on the first rank!',
    explanation: 'Qb1# — the queen moves to b1. The king on a1 is completely trapped by the White king on c1 and the queen on b1.',
  },
  {
    id: 'b050',
    title: 'Queen Corner Mate 3',
    fen: '8/k7/2K5/1Q6/8/8/8/8 w - - 0 1',
    solution: ["b5b7"],
    rating: 396,
    hint: 'The queen delivers checkmate on b7!',
    explanation: 'Qb7# — the queen moves to b7. The king on a7 is trapped: the White king on c6 controls a6 and b6, the queen covers a7 and b8.',
  },
  {
    id: 'b051',
    title: 'Queen and King Edge Mate',
    fen: '7k/5K2/8/8/8/8/8/6Q1 w - - 0 1',
    solution: ["g1g7"],
    rating: 400,
    hint: 'The queen and White king work together to deliver checkmate!',
    explanation: 'Qg7# — the queen delivers checkmate on g7. The king on h8 cannot escape: the queen covers g8, h7, and h6; the White king on f7 controls f8, g8, g7.',
  },
  {
    id: 'b052',
    title: 'Smothered Mate Classic',
    fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',
    solution: ["h6f7"],
    rating: 404,
    hint: 'The knight jumps to a square where the king is surrounded by its own pieces!',
    explanation: 'Nf7# — the knight leaps to f7, delivering checkmate. The king on h8 is smothered by its own rook on g8 and pawns on g7, h7.',
  },
  {
    id: 'b053',
    title: 'Queen Corner Mate 4',
    fen: '8/8/8/8/8/2K5/8/kQ6 w - - 0 1',
    solution: ["b1b2"],
    rating: 408,
    hint: 'The queen delivers checkmate beside the king!',
    explanation: 'Qb2# — the queen delivers checkmate on b2. The king on a1 is trapped by the queen on b2 and the White king on c3.',
  },
  {
    id: 'b054',
    title: 'King a8 Rook Mate 4',
    fen: 'k7/ppp5/8/8/8/8/8/4R2K w - - 0 1',
    solution: ["e1e8"],
    rating: 412,
    hint: 'The rook races to the 8th rank for checkmate!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on a8 is completely boxed in by pawns on a7, b7, c7 and the rook covers the entire 8th rank.',
  },
  {
    id: 'b055',
    title: "Scholar's Mate",
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    solution: ["h5f7"],
    rating: 416,
    hint: 'Look at f7 — it is only protected by the king!',
    explanation: 'Qxf7# — the famous Scholar\'s Mate! The queen captures on f7, supported by the bishop on c4. The Black king cannot escape. Always protect f7 in the opening!',
  },
  {
    id: 'b056',
    title: 'Corner King Rook Mate 12',
    fen: '7k/6pp/8/8/8/8/1R6/7K w - - 0 1',
    solution: ["b2b8"],
    rating: 420,
    hint: 'The rook races from the 2nd rank to the 8th!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. The king on h8 is trapped by g7 and h7 pawns.',
  },
  {
    id: 'b057',
    title: 'Corner King Rook Mate 13',
    fen: '7k/6pp/8/8/8/8/2R5/7K w - - 0 1',
    solution: ["c2c8"],
    rating: 424,
    hint: 'The c-rook strikes for checkmate!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The king on h8 is trapped by g7 and h7 pawns.',
  },
  {
    id: 'b058',
    title: 'Corner King Rook Mate 14',
    fen: '7k/6pp/8/8/8/8/8/R6K w - - 0 1',
    solution: ["a1a8"],
    rating: 428,
    hint: 'The rook slides to the 8th rank!',
    explanation: 'Ra8# — the rook delivers checkmate on a8. The king on h8 is trapped by g7 and h7 pawns.',
  },
  {
    id: 'b059',
    title: 'King f8 Rook Mate',
    fen: '5k2/4pppp/8/8/8/8/8/2R4K w - - 0 1',
    solution: ["c1c8"],
    rating: 432,
    hint: 'The c-rook delivers checkmate to the trapped king on f8!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The king on f8 is trapped: e7, f7, g7, h7 pawns block all lower escapes, and the rook controls the entire 8th rank.',
  },
  {
    id: 'b060',
    title: 'Queen Mate with King Support',
    fen: '6k1/5ppp/7K/8/8/8/8/6Q1 w - - 0 1',
    solution: ["g1g7"],
    rating: 436,
    hint: 'The queen captures on g7 for checkmate — the king on h6 protects it!',
    explanation: 'Qxg7# — the queen captures on g7, delivering checkmate. The White king on h6 protects the queen, so the Black king cannot capture it. The king on g8 has no escape.',
  },
  {
    id: 'b061',
    title: 'King a8 Rook Mate 5',
    fen: 'k7/pp6/8/8/8/8/8/5R1K w - - 0 1',
    solution: ["f1f8"],
    rating: 440,
    hint: 'The f-rook delivers checkmate to the corner king!',
    explanation: 'Rf8# — the rook delivers checkmate on f8. The king on a8 is trapped by pawns on a7 and b7.',
  },
  {
    id: 'b062',
    title: 'King b8 Rook Mate',
    fen: '1k6/pppp4/8/8/8/8/8/4R2K w - - 0 1',
    solution: ["e1e8"],
    rating: 444,
    hint: 'The e-rook delivers checkmate on the 8th rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on b8 is trapped by pawns on a7, b7, c7, d7 and the rook controls the entire 8th rank.',
  },
  {
    id: 'b063',
    title: 'Rook and Two Rooks',
    fen: '6k1/5ppp/8/8/8/8/8/2RR3K w - - 0 1',
    solution: ["c1c8"],
    rating: 448,
    hint: 'Two rooks cover the board — use one to deliver checkmate!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The other rook and pawns ensure the king has no escape.',
  },
  {
    id: 'b064',
    title: 'Queen Sweeps In',
    fen: '6k1/5ppp/8/8/8/8/8/Q5RK w - - 0 1',
    solution: ["a1a8"],
    rating: 452,
    hint: 'The queen races to the 8th rank!',
    explanation: 'Qa8# — the queen sweeps to a8, delivering checkmate. The rook on g1, pawns f7, g7, h7, and White king trap the Black king completely.',
  },
  {
    id: 'b065',
    title: 'Queen Corner Mate 5',
    fen: '8/k1K5/8/8/8/8/8/1Q6 w - - 0 1',
    solution: ["b1b7"],
    rating: 456,
    hint: 'The queen delivers checkmate with the king\'s help!',
    explanation: 'Qb7# — the queen delivers checkmate on b7. The king on a7 is trapped: the White king on c7 controls b8 and c8, the queen covers a7, b6, and the a-file.',
  },
  {
    id: 'b066',
    title: 'Queen Corner Mate 6',
    fen: '8/k1K5/8/8/8/8/8/1Q6 w - - 0 1',
    solution: ["b1b7"],
    rating: 460,
    hint: 'King and queen coordinate for back-rank mate!',
    explanation: 'Qb7# — the queen delivers checkmate on b7. The White king on c7 covers b8, while the queen covers a7, b6, and the entire a-file.',
  },
  {
    id: 'b067',
    title: 'Queen Back-Rank Mate',
    fen: 'k7/2K5/8/8/8/8/1Q6/8 w - - 0 1',
    solution: ["b2b8"],
    rating: 464,
    hint: 'Drive the queen to the 8th rank for checkmate!',
    explanation: 'Qb8# — the queen delivers checkmate on b8. The king on a8 is trapped: the White king on c7 covers b7 and b8 (protecting the queen), while the queen covers a8 via the b-file.',
  },
  {
    id: 'b068',
    title: 'Queen Mates With King Help',
    fen: '8/k1K5/8/8/8/8/8/1Q6 w - - 0 1',
    solution: ["b1b7"],
    rating: 468,
    hint: 'The queen and White king work together!',
    explanation: 'Qb7# — the queen delivers checkmate on b7. The White king on c7 covers b8 and b6, while the queen on b7 covers a7 and a8.',
  },
  {
    id: 'b069',
    title: 'Rook + Queen Combo',
    fen: '6k1/4pppp/8/8/8/8/8/Q5RK w - - 0 1',
    solution: ["a1a8"],
    rating: 472,
    hint: 'The queen delivers checkmate to the trapped king!',
    explanation: 'Qa8# — the queen sweeps to a8 delivering checkmate. Four pawns, the rook, and the White king ensure there is no escape.',
  },
  {
    id: 'b070',
    title: 'Rook From 2nd Rank Mate 1',
    fen: '6k1/5ppp/8/8/8/8/4R3/7K w - - 0 1',
    solution: ["e2e8"],
    rating: 476,
    hint: 'The e-file rook from 2nd rank strikes!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'b071',
    title: 'Rook From 2nd Rank Mate 2',
    fen: '6k1/5ppp/8/8/8/8/3R4/7K w - - 0 1',
    solution: ["d2d8"],
    rating: 480,
    hint: 'The d-rook from the 2nd rank delivers checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'b072',
    title: 'Rook From 2nd Rank Mate 3',
    fen: '6k1/5ppp/8/8/8/8/2R5/7K w - - 0 1',
    solution: ["c2c8"],
    rating: 484,
    hint: 'The c-rook from the 2nd rank delivers checkmate!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b073',
    title: 'Rook From 2nd Rank Mate 4',
    fen: '6k1/5ppp/8/8/8/8/1R6/7K w - - 0 1',
    solution: ["b2b8"],
    rating: 488,
    hint: 'The b-rook from the 2nd rank delivers checkmate!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b074',
    title: 'Rook From 3rd Rank Mate 1',
    fen: '6k1/5ppp/8/8/8/4R3/8/7K w - - 0 1',
    solution: ["e3e8"],
    rating: 492,
    hint: 'The e-rook from the 3rd rank strikes!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns trap the king on g8.',
  },
  {
    id: 'b075',
    title: 'Rook From 3rd Rank Mate 2',
    fen: '6k1/5ppp/8/8/8/3R4/8/7K w - - 0 1',
    solution: ["d3d8"],
    rating: 496,
    hint: 'The d-rook from the 3rd rank delivers checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'b076',
    title: 'Rook From 3rd Rank Mate 3',
    fen: '6k1/5ppp/8/8/8/2R5/8/7K w - - 0 1',
    solution: ["c3c8"],
    rating: 500,
    hint: 'The c-rook from the 3rd rank delivers checkmate!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. Three pawns cage the king on g8.',
  },
  {
    id: 'b077',
    title: 'Rook From 3rd Rank Mate 4',
    fen: '6k1/5ppp/8/8/8/1R6/8/7K w - - 0 1',
    solution: ["b3b8"],
    rating: 504,
    hint: 'The b-rook from the 3rd rank delivers checkmate!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b078',
    title: 'Rook From 4th Rank Mate 1',
    fen: '6k1/5ppp/8/8/4R3/8/8/7K w - - 0 1',
    solution: ["e4e8"],
    rating: 508,
    hint: 'The rook strikes from the 4th rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'b079',
    title: 'Rook From 4th Rank Mate 2',
    fen: '6k1/5ppp/8/8/3R4/8/8/7K w - - 0 1',
    solution: ["d4d8"],
    rating: 512,
    hint: 'The d-rook from the 4th rank delivers checkmate!',
    explanation: 'Rd4d8# — the rook delivers checkmate on d8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b080',
    title: 'Rook From 4th Rank Mate 3',
    fen: '6k1/5ppp/8/8/2R5/8/8/7K w - - 0 1',
    solution: ["c4c8"],
    rating: 516,
    hint: 'The c-rook strikes from the 4th rank!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'b081',
    title: 'Rook From 4th Rank Mate 4',
    fen: '6k1/5ppp/8/8/1R6/8/8/7K w - - 0 1',
    solution: ["b4b8"],
    rating: 520,
    hint: 'The b-rook strikes from the 4th rank!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b082',
    title: 'Rook From 5th Rank Mate 1',
    fen: '6k1/5ppp/8/4R3/8/8/8/7K w - - 0 1',
    solution: ["e5e8"],
    rating: 524,
    hint: 'The rook strikes from the 5th rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'b083',
    title: 'Rook From 5th Rank Mate 2',
    fen: '6k1/5ppp/8/3R4/8/8/8/7K w - - 0 1',
    solution: ["d5d8"],
    rating: 528,
    hint: 'The d-rook from the 5th rank delivers checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b084',
    title: 'Rook From 5th Rank Mate 3',
    fen: '6k1/5ppp/8/2R5/8/8/8/7K w - - 0 1',
    solution: ["c5c8"],
    rating: 532,
    hint: 'The c-rook from the 5th rank delivers checkmate!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. Three pawns cage the king on g8.',
  },
  {
    id: 'b085',
    title: 'Rook From 5th Rank Mate 4',
    fen: '6k1/5ppp/8/1R6/8/8/8/7K w - - 0 1',
    solution: ["b5b8"],
    rating: 536,
    hint: 'The b-rook from the 5th rank delivers checkmate!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b086',
    title: 'Queen From 2nd Rank Mate 1',
    fen: '6k1/5ppp/8/8/8/8/4Q3/7K w - - 0 1',
    solution: ["e2e8"],
    rating: 540,
    hint: 'The queen strikes from the 2nd rank!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'b087',
    title: 'Queen From 2nd Rank Mate 2',
    fen: '6k1/5ppp/8/8/8/8/3Q4/7K w - - 0 1',
    solution: ["d2d8"],
    rating: 544,
    hint: 'The d-queen from the 2nd rank delivers checkmate!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b088',
    title: 'Queen From 2nd Rank Mate 3',
    fen: '6k1/5ppp/8/8/8/8/2Q5/7K w - - 0 1',
    solution: ["c2c8"],
    rating: 548,
    hint: 'The c-queen from the 2nd rank delivers checkmate!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. Three pawns cage the king on g8.',
  },
  {
    id: 'b089',
    title: 'Queen From 2nd Rank Mate 4',
    fen: '6k1/5ppp/8/8/8/8/1Q6/7K w - - 0 1',
    solution: ["b2b8"],
    rating: 552,
    hint: 'The b-queen from the 2nd rank delivers checkmate!',
    explanation: 'Qb8# — the queen delivers checkmate on b8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b090',
    title: 'Double Rook Finish',
    fen: '7k/6pp/8/8/8/8/8/RR5K w - - 0 1',
    solution: ["a1a8"],
    rating: 556,
    hint: 'Two rooks work together for checkmate!',
    explanation: 'Ra8# — the rook delivers checkmate on a8. The rook on b1 covers the b-file and the king on h8 is trapped by g7 and h7 pawns.',
  },
  {
    id: 'b091',
    title: 'Double Rook 2',
    fen: '7k/5ppp/8/8/8/8/8/RR5K w - - 0 1',
    solution: ["a1a8"],
    rating: 560,
    hint: 'The a-rook delivers checkmate!',
    explanation: 'Ra8# — the rook delivers checkmate on a8. Three pawns trap the king on h8, and the rook on b1 provides backup.',
  },
  {
    id: 'b092',
    title: 'Queen and Rook',
    fen: '7k/5ppp/8/8/8/8/8/QR5K w - - 0 1',
    solution: ["a1a8"],
    rating: 564,
    hint: 'The queen races to the 8th rank for checkmate!',
    explanation: 'Qa8# — the queen delivers checkmate on a8. Three pawns and the rook on b1 leave the king on h8 with no escape.',
  },
  {
    id: 'b093',
    title: 'Two Rooks, Many Pawns',
    fen: '6k1/4pppp/8/8/8/8/8/RR5K w - - 0 1',
    solution: ["a1a8"],
    rating: 568,
    hint: 'Deliver checkmate with the first rook!',
    explanation: 'Ra8# — the rook delivers checkmate on a8. Four pawns and two rooks combine to eliminate any escape for the king on g8.',
  },
  {
    id: 'b094',
    title: 'Queen From 3rd Rank Mate 1',
    fen: '6k1/5ppp/8/8/8/4Q3/8/7K w - - 0 1',
    solution: ["e3e8"],
    rating: 572,
    hint: 'The e-queen from the 3rd rank delivers checkmate!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b095',
    title: 'Queen From 3rd Rank Mate 2',
    fen: '6k1/5ppp/8/8/8/3Q4/8/7K w - - 0 1',
    solution: ["d3d8"],
    rating: 576,
    hint: 'The d-queen from the 3rd rank delivers checkmate!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'b096',
    title: 'Five Pawns Rook Mate',
    fen: '4k3/3ppppp/8/8/8/8/8/1R5K w - - 0 1',
    solution: ["b1b8"],
    rating: 580,
    hint: 'Five pawns cage the king — use the b-file!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Five pawns from d7 to h7 completely cage the king on e8.',
  },
  {
    id: 'b097',
    title: 'Five Pawns Queen Mate',
    fen: '4k3/3ppppp/8/8/8/8/8/2Q4K w - - 0 1',
    solution: ["c1c8"],
    rating: 584,
    hint: 'The queen strikes for checkmate!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. Five pawns from d7 to h7 completely cage the king on e8.',
  },
  {
    id: 'b098',
    title: 'Ladder Mate Setup',
    fen: 'k7/2K5/8/8/8/8/1Q6/8 w - - 0 1',
    solution: ["b2b8"],
    rating: 588,
    hint: 'The queen delivers checkmate with the king\'s help!',
    explanation: 'Qb8# — the queen delivers checkmate on b8. The king on a8 cannot escape: the White king on c7 covers b7 and protects the queen on b8, while the queen covers a8 via the rank.',
  },
  {
    id: 'b099',
    title: 'Rook Back Rank',
    fen: '6k1/3p1ppp/8/8/8/8/8/4R2K w - - 0 1',
    solution: ["e1e8"],
    rating: 592,
    hint: 'The e-file is open — deliver checkmate!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on g8 is trapped by d7, f7, g7, h7 pawns.',
  },
  {
    id: 'b100',
    title: 'Queen Back Rank Final',
    fen: '6k1/3p1ppp/8/8/8/8/8/4Q2K w - - 0 1',
    solution: ["e1e8"],
    rating: 596,
    hint: 'The queen delivers checkmate on the 8th rank!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. The king on g8 is trapped by d7, f7, g7, h7 pawns.',
  },

  // ── INTERMEDIATE (rating 600-900) — multi-move combos ─────────────────────
  {
    id: 'i001',
    title: 'Sacrifice for Mate',
    fen: '6k1/4Qppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ["e7f7", "g8h8", "e1e8"],
    rating: 600,
    hint: 'Sacrifice the queen to drive the king to the corner, then the rook finishes!',
    explanation: 'Qxf7+! forces Kh8, then Re8# — the queen sacrifice drives the king to h8 where the rook delivers checkmate. Beautiful combination!',
  },
  {
    id: 'i002',
    title: 'Rook Sacrifice Deflection',
    fen: '2r3k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "c8e8", "a4e8"],
    rating: 603,
    hint: 'Sacrifice the rook to deflect the defender, then checkmate with the queen!',
    explanation: 'Re8+! Rxe8 (forced), Qxe8# — the rook sacrifice lures Black\'s rook to e8, setting up the queen checkmate. A classic deflection sacrifice!',
  },
  {
    id: 'i003',
    title: 'Arabian Mate',
    fen: '6k1/6pp/8/5N2/8/8/8/R5K1 w - - 0 1',
    solution: ["f5h6", "g8h8", "a1a8"],
    rating: 606,
    hint: 'The knight and rook deliver the famous Arabian Mate!',
    explanation: 'Nh6+! forces Kh8, then Ra8# — the knight checks and covers g8, forcing the king to h8 where the rook delivers checkmate. The Arabian Mate is one of chess\'s most beautiful patterns!',
  },
  {
    id: 'i004',
    title: 'Queen Sacrifice for Mate',
    fen: '6k1/4Qppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ["e7f7", "g8h8", "e1e8"],
    rating: 609,
    hint: 'Sacrifice the queen to drive the king to the edge!',
    explanation: 'Qxf7+! forces Kh8, then Re8# — the queen sacrifice drives the king to h8, and the rook delivers the decisive checkmate. Material sacrifices for forced checkmate are the most beautiful moves in chess!',
  },
  {
    id: 'i005',
    title: 'Rook Deflection Mate',
    fen: 'r5k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "a8e8", "a4e8"],
    rating: 612,
    hint: 'Sacrifice the rook to deflect the defender, then the queen mates!',
    explanation: 'Re8+! Rxe8 (forced), Qxe8# — the rook sacrifice lures Black\'s rook to e8, setting up the queen checkmate. Deflection sacrifices are a key tactical weapon!',
  },
  {
    id: 'i006',
    title: 'Back Rank Deflection',
    fen: '3r2k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "d8e8", "a4e8"],
    rating: 615,
    hint: 'Sacrifice the rook to deflect the defender, then the queen delivers checkmate!',
    explanation: 'Re8+! Rxe8 (forced), Qxe8# — the rook sacrifice deflects the rook from d8, and the queen delivers checkmate on e8. A beautiful back rank combination!',
  },
  {
    id: 'i007',
    title: 'Arabian Mate Variant',
    fen: '6k1/5Npp/8/8/8/8/8/R5K1 w - - 0 1',
    solution: ["f7h6", "g8h8", "a1a8"],
    rating: 618,
    hint: 'Move the knight to cover the escape square, then the rook strikes!',
    explanation: 'Nh6+! forces Kh8, then Ra8# — the knight moves to h6 covering g8, and the rook delivers checkmate on a8. Another gorgeous Arabian Mate!',
  },
  {
    id: 'i008',
    title: 'Knight Drives King',
    fen: '6k1/6pp/6N1/8/8/8/8/R5K1 w - - 0 1',
    solution: ["g6h8", "g8h8", "a1a8"],
    rating: 621,
    hint: 'The knight drives the king to h8 for the rook to deliver checkmate!',
    explanation: 'Nxh8! forces the king to recapture (Kxh8), then Ra8# — the knight sacrifice drives the king to h8 where the rook delivers checkmate with g7 and h7 pawns sealing the trap.',
  },
  {
    id: 'i009',
    title: 'Queen Sac Then Rook',
    fen: '6k1/4Qppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ["e7f7", "g8h8", "e1e8"],
    rating: 624,
    hint: 'The queen sacrifice opens a mating corridor for the rook!',
    explanation: 'Qxf7+! Kh8, Re8# — a queen sacrifice to force the king to the corner, then a rook delivers the decisive blow. Chess tactics at their finest!',
  },
  {
    id: 'i010',
    title: 'Double Rook Deflection',
    fen: '2r3k1/5ppp/8/8/Q7/8/8/3R2K1 w - - 0 1',
    solution: ["d1d8", "c8d8"],
    rating: 627,
    hint: 'Use the rook to deflect the defender and win decisive material!',
    explanation: 'Rxd8+! Rxd8 — the rook sacrifice deflects Black\'s rook, winning a decisive material advantage. Deflection is a key tactical weapon!',
  },
  {
    id: 'i011',
    title: 'Rook Sac Wins Material',
    fen: '2r3k1/1p3ppp/p7/4p3/8/1P3N2/P4PPP/3R2K1 w - - 0 1',
    solution: ["d1d8", "c8d8"],
    rating: 630,
    hint: 'Sacrifice the rook to deflect the defender and gain material!',
    explanation: 'Rxd8+! Rxd8 — White sacrifices the rook to deflect Black\'s rook from its defensive post, winning material. Deflection sacrifices create long-term positional advantages!',
  },
  {
    id: 'i012',
    title: 'Queen Delivers Checkmate',
    fen: '6k1/5ppp/8/8/8/3Q4/8/4R1K1 w - - 0 1',
    solution: ["d3d8"],
    rating: 633,
    hint: 'The queen can deliver checkmate in one move from the 3rd rank!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. The king on g8 is trapped by f7, g7, h7 pawns and the queen controls the entire 8th rank.',
  },
  {
    id: 'i013',
    title: 'Rook Sacrifice Exchange',
    fen: '3r2k1/5ppp/8/8/2Q5/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "d8e8"],
    rating: 636,
    hint: 'Deflect the rook, then use the queen to win material!',
    explanation: 'Re8+! Rxe8 — the rook sacrifice deflects Black\'s rook, giving White a decisive material advantage. The queen now dominates the board.',
  },
  {
    id: 'i014',
    title: 'Two Rook Mate',
    fen: '7k/6R1/5R1K/8/8/8/8/8 w - - 0 1',
    solution: ["f6f8"],
    rating: 639,
    hint: 'One rook delivers checkmate with the other covering key squares!',
    explanation: 'Rf8# — the rook on f6 moves to f8, delivering checkmate. The king on h8 is trapped: the rook on g7 covers g8, and the White king on h6 covers g7, h7. Rook on f8 completes the mating net.',
  },
  {
    id: 'i015',
    title: 'Discovered Check Wins',
    fen: '6k1/4Qppp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: ["e7f7", "g8h8", "d1d8"],
    rating: 642,
    hint: 'Sacrifice the queen to drive the king to the corner, then the rook finishes!',
    explanation: 'Qxf7+! forces Kh8, then Rd8# — the queen sacrifice drives the king to h8 where the rook delivers checkmate. Beautiful combination!',
  },
  {
    id: 'i016',
    title: 'Rook Deflects Defender',
    fen: '1r4k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "b8e8", "a4e8"],
    rating: 645,
    hint: 'Sacrifice the rook to deflect the rook defender, then checkmate!',
    explanation: 'Re8+! Rxe8 (forced), Qxe8# — the rook sacrifice lures Black\'s rook from b8 to e8, setting up a decisive queen checkmate. Deflection in action!',
  },
  {
    id: 'i017',
    title: 'Rook Sacrifice Pattern',
    fen: '1r4k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "b8e8", "a4e8"],
    rating: 648,
    hint: 'Trade the rook for the defender and deliver checkmate!',
    explanation: 'Re8+! Rxe8, Qxe8# — a beautiful deflection sacrifice. The rook lures Black\'s rook to e8, allowing the queen to deliver checkmate on e8.',
  },
  {
    id: 'i018',
    title: 'Queen Takes on Checkmate Square',
    fen: '2r3k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "c8e8", "a4e8"],
    rating: 651,
    hint: 'Sacrifice the rook, then the queen delivers the knockout!',
    explanation: 'Re8+! Rxe8, Qxe8# — classic deflection. The rook sacrifice draws the defender to e8, and the queen delivers checkmate. One of chess\'s most satisfying patterns!',
  },
  {
    id: 'i019',
    title: 'Knight Check Wins',
    fen: '6k1/4Qppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ["e7f7", "g8h8", "e1e8"],
    rating: 654,
    hint: 'Sacrifice the queen to drive the king to the corner, then the rook delivers checkmate!',
    explanation: 'Qxf7+! forces Kh8, then Re8# — the queen sacrifice drives the king to h8 where the rook delivers checkmate. Classic queen sacrifice combination!',
  },
  {
    id: 'i020',
    title: 'Knight Fork Setup',
    fen: 'r3k3/8/8/4N3/8/8/8/4K3 w - - 0 1',
    solution: ["e5c6", "e8d7"],
    rating: 657,
    hint: 'The knight forks the king and rook to win material!',
    explanation: 'Nc6+! (fork) Kd7 — the knight delivers check while forking the rook on a8. The king must move, and White wins the rook. Knight forks are a key tactical weapon!',
  },
  {
    id: 'i021',
    title: 'Back Rank Combination',
    fen: '3r2k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "d8e8", "a4e8"],
    rating: 660,
    hint: 'Sacrifice the rook to deflect the defender, then the queen delivers checkmate!',
    explanation: 'Re8+! Rxe8 (forced), Qxe8# — the rook sacrifice deflects the rook from d8, and the queen delivers checkmate on e8. A beautiful back rank combination!',
  },
  {
    id: 'i022',
    title: 'Rook Deflects to Win',
    fen: '5k2/1r3ppp/8/8/4R3/8/8/5QK1 w - - 0 1',
    solution: ["e4e7", "b7e7"],
    rating: 663,
    hint: 'The rook goes to e7 to deflect the defender!',
    explanation: 'Rxe7! Rxe7 — White deflects Black\'s rook from its defensive position by forcing it to e7. This wins material and opens up decisive threats.',
  },
  {
    id: 'i023',
    title: 'Knight Check Then Queen',
    fen: '6k1/4Qppp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: ["e7f7", "g8h8", "d1d8"],
    rating: 666,
    hint: 'Sacrifice the queen to drive the king to the corner, then the rook finishes!',
    explanation: 'Qxf7+! forces Kh8, then Rd8# — the queen sacrifice drives the king to h8 where the rook delivers checkmate. A powerful queen sacrifice pattern!',
  },
  {
    id: 'i024',
    title: 'Promotion Avoids Stalemate',
    fen: '8/P7/8/8/8/8/2K5/k7 w - - 0 1',
    solution: ["a7a8r"],
    rating: 669,
    hint: 'Promote to a rook, not a queen — avoid stalemate!',
    explanation: 'a8=R# — promoting to a queen would cause stalemate since the Black king on a1 would have no legal moves! The rook on a8 delivers checkmate while the White king on c2 covers b1 and b2.',
  },
  {
    id: 'i025',
    title: 'Rook Corner Checkmate',
    fen: '6k1/5ppp/8/4R3/8/8/8/6K1 w - - 0 1',
    solution: ["e5e8"],
    rating: 672,
    hint: 'The rook delivers checkmate from the 5th rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on g8 is trapped by f7, g7, h7 pawns and the rook covers the entire 8th rank.',
  },
  {
    id: 'i026',
    title: 'Rook Swings for Checkmate',
    fen: '7k/5KRp/8/8/8/8/8/8 w - - 0 1',
    solution: ["g7g8"],
    rating: 675,
    hint: 'The rook delivers checkmate on g8 — the king on f7 covers the rook!',
    explanation: 'Rg8# — the rook moves from g7 to g8, delivering checkmate! The king on h8 cannot escape: h7 is a pawn, and the White king on f7 covers the g8 square, protecting the rook.',
  },
  {
    id: 'i027',
    title: 'Rook Slide Checkmate',
    fen: '7k/6pp/8/8/8/8/8/5Q1K w - - 0 1',
    solution: ["f1f8"],
    rating: 678,
    hint: 'The queen strikes along the f-file for checkmate!',
    explanation: 'Qf8# — the queen delivers checkmate on f8. The king on h8 is trapped by g7, h7 pawns and the queen covers the entire 8th rank.',
  },
  {
    id: 'i028',
    title: 'Rook Checkmate Combo',
    fen: '6k1/5ppp/8/4R3/8/8/8/6K1 w - - 0 1',
    solution: ["e5e8"],
    rating: 681,
    hint: 'The rook can deliver checkmate from the 5th rank!',
    explanation: 'Re8# — the rook jumps to e8, delivering checkmate! The king on g8 is trapped by f7, g7, h7 pawns and cannot capture the rook (too far).',
  },
  {
    id: 'i029',
    title: 'Rook From Fifth',
    fen: '6k1/5ppp/8/4R3/8/8/8/6K1 w - - 0 1',
    solution: ["e5e8"],
    rating: 684,
    hint: 'The rook delivers checkmate from the 5th rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on g8 is completely trapped by three pawns on f7, g7, h7.',
  },
  {
    id: 'i030',
    title: 'Rook Strikes Far',
    fen: '6k1/5ppp/8/3R4/8/8/8/6K1 w - - 0 1',
    solution: ["d5d8"],
    rating: 687,
    hint: 'The rook delivers checkmate from the 5th rank!',
    explanation: 'Rd8# — the rook leaps to d8, delivering checkmate! The king on g8 cannot escape past f7, g7, h7 pawns, and the rook controls the full 8th rank.',
  },
  {
    id: 'i031',
    title: 'Rook and Pawns',
    fen: '7k/5ppp/8/4R3/8/8/8/6K1 w - - 0 1',
    solution: ["e5e8"],
    rating: 690,
    hint: 'Three pawns and the rook seal the corner king\'s fate!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 and the rook combine to trap the king on h8.',
  },
  {
    id: 'i032',
    title: 'Queen Strikes From Afar',
    fen: '6k1/5ppp/8/3Q4/8/8/8/6K1 w - - 0 1',
    solution: ["d5d8"],
    rating: 693,
    hint: 'The queen delivers checkmate from the 5th rank!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. The king on g8 is trapped by f7, g7, h7 pawns and the queen controls the entire 8th rank.',
  },
  {
    id: 'i033',
    title: 'Rook 4th Rank Mate',
    fen: '6k1/5ppp/8/8/4R3/8/8/6K1 w - - 0 1',
    solution: ["e4e8"],
    rating: 696,
    hint: 'The rook can strike from the 4th rank all the way to the 8th!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on g8 is trapped by pawns f7, g7, h7.',
  },
  {
    id: 'i034',
    title: 'Rook 4th Rank Corner Mate',
    fen: '7k/5ppp/8/8/4R3/8/8/6K1 w - - 0 1',
    solution: ["e4e8"],
    rating: 699,
    hint: 'Launch the rook from the 4th rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on h8.',
  },
  {
    id: 'i035',
    title: 'Queen 4th Rank Mate',
    fen: '6k1/5ppp/8/8/4Q3/8/8/6K1 w - - 0 1',
    solution: ["e4e8"],
    rating: 702,
    hint: 'The queen delivers checkmate from the 4th rank!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. The king on g8 is trapped by f7, g7, h7 pawns.',
  },
  {
    id: 'i036',
    title: 'Queen 3rd Rank Mate',
    fen: '6k1/5ppp/8/8/8/4Q3/8/6K1 w - - 0 1',
    solution: ["e3e8"],
    rating: 705,
    hint: 'The queen can reach the 8th rank from the 3rd!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. The king on g8 is trapped by three pawns.',
  },
  {
    id: 'i037',
    title: 'Rook Skips Ranks',
    fen: '7k/5ppp/8/8/8/4R3/8/6K1 w - - 0 1',
    solution: ["e3e8"],
    rating: 708,
    hint: 'The rook can travel from the 3rd rank to the 8th!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on h8.',
  },
  {
    id: 'i038',
    title: 'Promotion Then Mate',
    fen: '8/1P6/8/8/8/8/8/k1K5 w - - 0 1',
    solution: ["b7b8q", "a1a2", "b8b2"],
    rating: 711,
    hint: 'Promote the pawn and use the new queen to deliver checkmate!',
    explanation: 'b8=Q! Ka2, Qb2# — the pawn promotes, the king tries to escape, but the queen delivers checkmate on b2 with the White king on c1 controlling key squares.',
  },
  {
    id: 'i039',
    title: 'Promotion Checkmate Direct',
    fen: '8/P7/8/8/8/8/8/k1K5 w - - 0 1',
    solution: ["a7a8q"],
    rating: 714,
    hint: 'Promote the pawn and deliver immediate checkmate!',
    explanation: 'a8=Q# — the pawn promotes to a queen, immediately delivering checkmate! The king on a1 is trapped by the White king on c1 and the queen on a8.',
  },
  {
    id: 'i040',
    title: 'Rook Corner Mate',
    fen: '6k1/4Qppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ["e7f7", "g8h8", "e1e8"],
    rating: 717,
    hint: 'Sacrifice the queen to drive the king to the corner, then the rook delivers checkmate!',
    explanation: 'Qxf7+! forces Kh8, then Re8# — the queen sacrifice drives the king to h8 where the rook delivers checkmate. A classic queen sacrifice pattern!',
  },
  {
    id: 'i041',
    title: 'Queen Then Rook',
    fen: '8/8/8/8/8/8/2K5/kQ6 w - - 0 1',
    solution: ["b1b2"],
    rating: 720,
    hint: 'The queen delivers checkmate!',
    explanation: 'Qb2# — the queen delivers checkmate on b2! The king on a1 is trapped: the White king on c2 controls b2\'s neighboring squares, and the queen covers the entire b-file.',
  },
  {
    id: 'i042',
    title: 'King and Rook Trap',
    fen: '3r2k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "d8e8", "a4e8"],
    rating: 723,
    hint: 'Sacrifice the rook to deflect the defender, then the queen delivers checkmate!',
    explanation: 'Re8+! Rxe8 (forced), Qxe8# — the rook sacrifice deflects the rook from d8, and the queen delivers checkmate on e8. A back rank combination!',
  },
  {
    id: 'i043',
    title: 'Rook Controls Rank',
    fen: '8/k7/1K6/R7/8/8/8/8 w - - 0 1',
    solution: ["a5a7"],
    rating: 726,
    hint: 'The rook delivers checkmate on the 7th rank!',
    explanation: 'Ra7# — the rook delivers checkmate on a7! The king on a7 is in check from the rook. The White king on b6 covers b7 and b8, while the rook covers the entire 7th rank. King a7 has no escape.',
  },
  {
    id: 'i044',
    title: 'Queen Rook Two-Move Mate',
    fen: '5k2/4Rppp/8/8/8/8/8/5QK1 w - - 0 1',
    solution: ["e7f7", "f8g8"],
    rating: 729,
    hint: 'Use the rook to force the king to a mating square!',
    explanation: 'Rxf7+! Kg8 — the rook captures on f7 with check, forcing the king to g8. White wins decisive material with a crushing position.',
  },
  {
    id: 'i045',
    title: 'Knight Fork then Mate',
    fen: '2r3k1/5ppp/8/8/Q7/8/8/4R1K1 w - - 0 1',
    solution: ["e1e8", "c8e8", "a4e8"],
    rating: 732,
    hint: 'Sacrifice the rook to deflect the defender, then checkmate with the queen!',
    explanation: 'Re8+! Rxe8 (forced), Qxe8# — the rook sacrifice lures Black\'s rook from c8 to e8, and the queen delivers checkmate. A deflection sacrifice!',
  },
  {
    id: 'i046',
    title: 'Arabian Mate 4',
    fen: '6k1/4pNpp/8/8/8/8/8/R5K1 w - - 0 1',
    solution: ["f7h6", "g8h8", "a1a8"],
    rating: 735,
    hint: 'Move the knight to cover key squares, then rook delivers mate!',
    explanation: 'Nh6+! forces Kh8, then Ra8# — the knight delivers check and covers g8, forcing the king to h8 where the rook delivers checkmate.',
  },
  {
    id: 'i047',
    title: 'Rook Captures for Mate',
    fen: '7k/6pp/8/8/8/8/8/5R1K w - - 0 1',
    solution: ["f1f8"],
    rating: 738,
    hint: 'The rook slides up the f-file for checkmate!',
    explanation: 'Rf8# — the rook delivers checkmate on f8. The king on h8 cannot escape: g7 and h7 are pawns, and the rook covers the entire 8th rank.',
  },
  {
    id: 'i048',
    title: 'Mating Net',
    fen: '7k/5ppp/8/8/8/8/8/4R2K w - - 0 1',
    solution: ["e1e8"],
    rating: 741,
    hint: 'The rook delivers checkmate from the 1st rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on h8 cannot escape: f7, g7, h7 are pawns, and the rook covers the entire 8th rank.',
  },
  {
    id: 'i049',
    title: 'Queen Hunt',
    fen: '7k/5ppp/8/8/8/8/8/3Q3K w - - 0 1',
    solution: ["d1d8"],
    rating: 744,
    hint: 'The queen strikes for checkmate from the first rank!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. The king on h8 cannot escape: f7, g7, h7 are pawns, and the queen covers the entire 8th rank.',
  },
  {
    id: 'i050',
    title: 'Queen Diagonal Mate',
    fen: '7k/5ppp/8/8/8/8/8/2Q4K w - - 0 1',
    solution: ["c1c8"],
    rating: 747,
    hint: 'The queen delivers checkmate from the c-file!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. The king on h8 cannot escape: f7, g7, h7 are pawns, and the queen covers the entire 8th rank.',
  },
  {
    id: 'i051',
    title: 'Rook Mates From 3rd',
    fen: '7k/5KRp/8/8/8/8/8/8 w - - 0 1',
    solution: ["g7g8"],
    rating: 750,
    hint: 'The rook delivers checkmate on g8 — the king covers the square!',
    explanation: 'Rg8# — the rook moves to g8, delivering checkmate! The king on h8 cannot escape: h7 is a pawn, the White king on f7 covers g8, and the rook controls the 8th rank.',
  },
  {
    id: 'i052',
    title: 'Rook From 3rd to 8th',
    fen: '7k/5ppp/8/8/8/3R4/8/6K1 w - - 0 1',
    solution: ["d3d8"],
    rating: 753,
    hint: 'The rook leaps to d8 for checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. The king on h8 is completely trapped: f7, g7, h7 are pawns and the rook covers the entire 8th rank.',
  },
  {
    id: 'i053',
    title: 'Rook From 2nd Rank',
    fen: '7k/5ppp/8/8/8/8/3R4/6K1 w - - 0 1',
    solution: ["d2d8"],
    rating: 756,
    hint: 'Launch the rook from the 2nd rank to deliver checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. The king on h8 is trapped by f7, g7, h7 pawns and the rook covers the entire 8th rank.',
  },
  {
    id: 'i054',
    title: 'Rook Strikes From Behind',
    fen: '7k/5ppp/8/8/8/8/4R3/6K1 w - - 0 1',
    solution: ["e2e8"],
    rating: 759,
    hint: 'The rook delivers checkmate from the 2nd rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on h8 is completely trapped by three pawns f7, g7, h7.',
  },
  {
    id: 'i055',
    title: 'Two Rooks Coordination',
    fen: '7k/5ppp/8/8/8/8/8/4RR1K w - - 0 1',
    solution: ["e1e8"],
    rating: 762,
    hint: 'Use one of the two rooks for checkmate!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 completely trap the king on h8, and the rook on f1 provides backup.',
  },
  {
    id: 'i056',
    title: 'Two Rooks Easy Finish',
    fen: '6k1/5ppp/8/8/8/8/8/2RR3K w - - 0 1',
    solution: ["c1c8"],
    rating: 765,
    hint: 'Send one rook to the 8th rank!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. Three pawns trap the king on g8, and the rook on d1 provides additional coverage.',
  },
  {
    id: 'i057',
    title: 'Rook Lift Mate',
    fen: '7k/5ppp/8/4R3/8/8/8/7K w - - 0 1',
    solution: ["e5e8"],
    rating: 768,
    hint: 'The rook lifts to the 8th rank for checkmate!',
    explanation: 'Re8# — the rook lifts to e8, delivering checkmate! The king on h8 is trapped by three pawns f7, g7, h7 and the rook covers the entire 8th rank.',
  },
  {
    id: 'i058',
    title: 'Queen Lift Mate',
    fen: '7k/5ppp/8/4Q3/8/8/8/7K w - - 0 1',
    solution: ["e5e8"],
    rating: 771,
    hint: 'The queen lifts to the 8th rank for checkmate!',
    explanation: 'Qe8# — the queen lifts to e8, delivering checkmate. The king on h8 is trapped by three pawns.',
  },
  {
    id: 'i059',
    title: 'Rook Runs Down King',
    fen: '6k1/5ppp/8/4R3/8/8/8/7K w - - 0 1',
    solution: ["e5e8"],
    rating: 774,
    hint: 'The rook lifts to e8 for checkmate!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 completely trap the king on g8.',
  },
  {
    id: 'i060',
    title: 'Queen Runs Down King',
    fen: '6k1/5ppp/8/4Q3/8/8/8/7K w - - 0 1',
    solution: ["e5e8"],
    rating: 777,
    hint: 'The queen delivers checkmate from the 5th rank!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. Three pawns f7, g7, h7 completely trap the king on g8.',
  },
  {
    id: 'i061',
    title: 'Rook Mates 3',
    fen: '7k/5ppp/8/3R4/8/8/8/7K w - - 0 1',
    solution: ["d5d8"],
    rating: 780,
    hint: 'The d-rook delivers checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Three pawns f7, g7, h7 trap the king on h8 and the rook covers the entire 8th rank.',
  },
  {
    id: 'i062',
    title: 'Queen Mates 3',
    fen: '7k/5ppp/8/3Q4/8/8/8/7K w - - 0 1',
    solution: ["d5d8"],
    rating: 783,
    hint: 'The queen delivers checkmate from the 5th rank!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Three pawns f7, g7, h7 trap the king on h8.',
  },
  {
    id: 'i063',
    title: 'Rook From 6th',
    fen: '7k/5ppp/3R4/8/8/8/8/7K w - - 0 1',
    solution: ["d6d8"],
    rating: 786,
    hint: 'The rook advances to the 8th rank!',
    explanation: 'Rd8# — the rook advances to d8, delivering checkmate. The king on h8 is trapped by f7, g7, h7 pawns.',
  },
  {
    id: 'i064',
    title: 'Queen From 6th',
    fen: '7k/5ppp/3Q4/8/8/8/8/7K w - - 0 1',
    solution: ["d6d8"],
    rating: 789,
    hint: 'The queen moves to the 8th rank for checkmate!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Three pawns trap the king on h8.',
  },
  {
    id: 'i065',
    title: 'Rook From 5th f-file',
    fen: '6k1/4pppp/8/2R5/8/8/8/7K w - - 0 1',
    solution: ["c5c8"],
    rating: 792,
    hint: 'Slide the rook up the c-file for checkmate!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The king on g8 cannot escape: four pawns e7, f7, g7, h7 block all lower escapes, and the rook covers the entire 8th rank.',
  },
  {
    id: 'i066',
    title: 'Queen From 5th f-file',
    fen: '6k1/4pppp/8/2Q5/8/8/8/7K w - - 0 1',
    solution: ["c5c8"],
    rating: 795,
    hint: 'The queen delivers checkmate from the c-file!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. The king on g8 is completely trapped by four pawns e7, f7, g7, h7 and the queen covers the entire 8th rank.',
  },
  {
    id: 'i067',
    title: 'Rook From 4th f-file',
    fen: '6k1/4pppp/8/8/2R5/8/8/7K w - - 0 1',
    solution: ["c4c8"],
    rating: 798,
    hint: 'The rook can reach the 8th rank from the 4th via c-file!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The king on g8 is trapped by four pawns e7, f7, g7, h7 and the rook covers the entire 8th rank.',
  },
  {
    id: 'i068',
    title: 'Queen From 4th f-file',
    fen: '6k1/4pppp/8/8/2Q5/8/8/7K w - - 0 1',
    solution: ["c4c8"],
    rating: 801,
    hint: 'The queen delivers checkmate from the 4th rank via c-file!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. The king on g8 is completely trapped by four pawns and the queen controls the entire 8th rank.',
  },
  {
    id: 'i069',
    title: 'King and Rook Checkmate',
    fen: '6k1/5ppp/8/4R3/8/8/8/7K w - - 0 1',
    solution: ["e5e8"],
    rating: 804,
    hint: 'The rook delivers checkmate from the 5th rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on g8 cannot escape: f7, g7, h7 pawns block all lower escapes, and the rook covers the entire 8th rank.',
  },
  {
    id: 'i070',
    title: 'King Controls Escape Squares',
    fen: '7k/5ppp/8/4R3/8/8/8/7K w - - 0 1',
    solution: ["e5e8"],
    rating: 807,
    hint: 'The rook delivers checkmate from the 5th rank to the corner king!',
    explanation: 'Re8# — the rook delivers checkmate on e8. The king on h8 cannot escape: f7, g7, h7 are pawns, and the rook covers the entire 8th rank.',
  },
  {
    id: 'i071',
    title: 'Rook Gives Check',
    fen: '6k1/5ppp/8/8/8/8/4R3/7K w - - 0 1',
    solution: ["e2e8"],
    rating: 810,
    hint: 'The rook delivers checkmate from the 2nd rank!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on g8 and the rook covers the entire 8th rank.',
  },
  {
    id: 'i072',
    title: 'Queen Gives Check',
    fen: '6k1/5ppp/8/8/8/8/4Q3/7K w - - 0 1',
    solution: ["e2e8"],
    rating: 813,
    hint: 'The queen delivers checkmate from the 2nd rank!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. The king on g8 is trapped by f7, g7, h7 pawns and the queen controls the entire 8th rank.',
  },
  {
    id: 'i073',
    title: 'Corner Mate Four Pawns',
    fen: '7k/5ppp/8/8/8/8/3R4/7K w - - 0 1',
    solution: ["d2d8"],
    rating: 816,
    hint: 'Three pawns cage the king — deliver checkmate via the d-file!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Three pawns f7, g7, h7 completely trap the king on h8.',
  },
  {
    id: 'i074',
    title: 'Rook From 2nd to g8',
    fen: '7k/5KRp/8/8/8/8/8/8 w - - 0 1',
    solution: ["g7g8"],
    rating: 819,
    hint: 'The rook slides to g8 — the king covers the square!',
    explanation: 'Rg8# — the rook delivers checkmate on g8. The king on h8 cannot escape: h7 is a pawn, and the White king on f7 covers g8, protecting the rook from capture.',
  },
  {
    id: 'i075',
    title: 'Rook Runs Up g-file',
    fen: '7k/5ppp/8/8/8/8/3R4/7K w - - 0 1',
    solution: ["d2d8"],
    rating: 822,
    hint: 'The d-rook runs to the 8th rank for checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Three pawns f7, g7, h7 completely trap the king on h8 and the rook covers the entire 8th rank.',
  },
  {
    id: 'i076',
    title: 'Queen Strikes From 2nd',
    fen: '7k/5ppp/8/8/8/8/3Q4/7K w - - 0 1',
    solution: ["d2d8"],
    rating: 825,
    hint: 'The queen delivers checkmate from the 2nd rank via the d-file!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. The king on h8 cannot escape: f7, g7, h7 are pawns, and the queen covers the entire 8th rank.',
  },
  {
    id: 'i077',
    title: 'Rook Three Rank Jump',
    fen: '7k/4pppp/8/8/3R4/8/8/7K w - - 0 1',
    solution: ["d4d8"],
    rating: 828,
    hint: 'The rook leaps from the 4th rank to the 8th!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Four pawns e7, f7, g7, h7 completely trap the king on h8.',
  },
  {
    id: 'i078',
    title: 'Queen Three Rank Jump',
    fen: '7k/4pppp/8/8/3Q4/8/8/7K w - - 0 1',
    solution: ["d4d8"],
    rating: 831,
    hint: 'The queen jumps from the 4th rank to the 8th!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Four pawns e7, f7, g7, h7 cage the king on h8 completely.',
  },
  {
    id: 'i079',
    title: 'Rook From 6th to 8th',
    fen: '7k/4pppp/3R4/8/8/8/8/7K w - - 0 1',
    solution: ["d6d8"],
    rating: 834,
    hint: 'The rook jumps two ranks to deliver checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Four pawns completely trap the king on h8.',
  },
  {
    id: 'i080',
    title: 'Queen From 6th to 8th',
    fen: '7k/4pppp/3Q4/8/8/8/8/7K w - - 0 1',
    solution: ["d6d8"],
    rating: 837,
    hint: 'The queen jumps to the 8th rank for checkmate!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Four pawns from e7 to h7 cage the king on h8.',
  },
  {
    id: 'i081',
    title: 'Rook Uses c-file',
    fen: '6k1/4pppp/8/8/2R5/8/8/7K w - - 0 1',
    solution: ["c4c8"],
    rating: 840,
    hint: 'The c-rook delivers checkmate from the 4th rank!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. The king on g8 is trapped by four pawns e7, f7, g7, h7.',
  },
  {
    id: 'i082',
    title: 'Queen Uses c-file',
    fen: '6k1/4pppp/8/8/2Q5/8/8/7K w - - 0 1',
    solution: ["c4c8"],
    rating: 843,
    hint: 'The queen uses the c-file for checkmate!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. Four pawns completely trap the king on g8.',
  },
  {
    id: 'i083',
    title: 'Rook Uses b-file',
    fen: '6k1/4pppp/8/8/1R6/8/8/7K w - - 0 1',
    solution: ["b4b8"],
    rating: 846,
    hint: 'The b-rook delivers checkmate!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Four pawns e7, f7, g7, h7 completely trap the king on g8.',
  },
  {
    id: 'i084',
    title: 'Queen Uses b-file',
    fen: '6k1/4pppp/8/8/1Q6/8/8/7K w - - 0 1',
    solution: ["b4b8"],
    rating: 849,
    hint: 'The queen uses the b-file for checkmate!',
    explanation: 'Qb8# — the queen delivers checkmate on b8. Four pawns completely trap the king on g8.',
  },
  {
    id: 'i085',
    title: 'Rook a-file Four Pawns',
    fen: '6k1/4pppp/8/8/R7/8/8/7K w - - 0 1',
    solution: ["a4a8"],
    rating: 852,
    hint: 'The a-rook strikes for checkmate!',
    explanation: 'Ra8# — the rook delivers checkmate on a8. Four pawns from e7 to h7 cage the king on g8.',
  },
  {
    id: 'i086',
    title: 'Queen a-file Four Pawns',
    fen: '6k1/4pppp/8/8/Q7/8/8/7K w - - 0 1',
    solution: ["a4a8"],
    rating: 855,
    hint: 'The queen strikes from the a-file!',
    explanation: 'Qa8# — the queen delivers checkmate on a8. Four pawns completely trap the king on g8.',
  },
  {
    id: 'i087',
    title: 'Rook a2-a8',
    fen: '6k1/5ppp/8/8/8/8/R7/7K w - - 0 1',
    solution: ["a2a8"],
    rating: 858,
    hint: 'The rook runs up the a-file for checkmate!',
    explanation: 'Ra8# — the rook delivers checkmate on a8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'i088',
    title: 'Queen a2-a8',
    fen: '6k1/5ppp/8/8/8/8/Q7/7K w - - 0 1',
    solution: ["a2a8"],
    rating: 861,
    hint: 'The queen uses the a-file for checkmate!',
    explanation: 'Qa8# — the queen delivers checkmate on a8. Three pawns trap the king on g8.',
  },
  {
    id: 'i089',
    title: 'Rook b2-b8',
    fen: '6k1/5ppp/8/8/8/8/1R6/7K w - - 0 1',
    solution: ["b2b8"],
    rating: 864,
    hint: 'The rook races up the b-file!',
    explanation: 'Rb8# — the rook delivers checkmate on b8. Three pawns trap the king on g8 and the rook covers the entire 8th rank.',
  },
  {
    id: 'i090',
    title: 'Queen b2-b8',
    fen: '6k1/5ppp/8/8/8/8/1Q6/7K w - - 0 1',
    solution: ["b2b8"],
    rating: 867,
    hint: 'The queen uses the b-file for checkmate!',
    explanation: 'Qb8# — the queen delivers checkmate on b8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'i091',
    title: 'Rook c2-c8',
    fen: '6k1/5ppp/8/8/8/8/2R5/7K w - - 0 1',
    solution: ["c2c8"],
    rating: 870,
    hint: 'The c-rook delivers checkmate from the 2nd rank!',
    explanation: 'Rc8# — the rook delivers checkmate on c8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'i092',
    title: 'Queen c2-c8',
    fen: '6k1/5ppp/8/8/8/8/2Q5/7K w - - 0 1',
    solution: ["c2c8"],
    rating: 873,
    hint: 'The queen uses the c-file for checkmate!',
    explanation: 'Qc8# — the queen delivers checkmate on c8. Three pawns trap the king on g8.',
  },
  {
    id: 'i093',
    title: 'Rook d2-d8',
    fen: '6k1/5ppp/8/8/8/8/3R4/7K w - - 0 1',
    solution: ["d2d8"],
    rating: 876,
    hint: 'The d-rook delivers checkmate from the 2nd rank!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. Three pawns f7, g7, h7 trap the king on g8.',
  },
  {
    id: 'i094',
    title: 'Queen d2-d8',
    fen: '6k1/5ppp/8/8/8/8/3Q4/7K w - - 0 1',
    solution: ["d2d8"],
    rating: 879,
    hint: 'The queen strikes from the d-file!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. Three pawns f7, g7, h7 cage the king on g8.',
  },
  {
    id: 'i095',
    title: 'Rook e2-e8 Corner',
    fen: '7k/5ppp/8/8/8/8/4R3/7K w - - 0 1',
    solution: ["e2e8"],
    rating: 882,
    hint: 'The e-rook delivers checkmate to the corner king!',
    explanation: 'Re8# — the rook delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on h8.',
  },
  {
    id: 'i096',
    title: 'Queen e2-e8 Corner',
    fen: '7k/5ppp/8/8/8/8/4Q3/7K w - - 0 1',
    solution: ["e2e8"],
    rating: 885,
    hint: 'The queen strikes from e2 to e8!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. Three pawns f7, g7, h7 trap the king on h8.',
  },
  {
    id: 'i097',
    title: 'Rook f2-f8 Corner',
    fen: '7k/6pp/8/8/8/8/5R2/7K w - - 0 1',
    solution: ["f2f8"],
    rating: 888,
    hint: 'The f-rook delivers checkmate to the corner king!',
    explanation: 'Rf8# — the rook delivers checkmate on f8. Two pawns g7, h7 trap the king on h8 and the rook covers the entire 8th rank.',
  },
  {
    id: 'i098',
    title: 'Queen f2-f8 Corner',
    fen: '7k/6pp/8/8/8/8/5Q2/7K w - - 0 1',
    solution: ["f2f8"],
    rating: 891,
    hint: 'The queen strikes from f2 to f8!',
    explanation: 'Qf8# — the queen delivers checkmate on f8. Two pawns g7, h7 trap the king on h8 and the queen covers the entire 8th rank.',
  },
  {
    id: 'i099',
    title: 'Rook g-file Corner',
    fen: '7k/5KRp/8/8/8/8/8/8 w - - 0 1',
    solution: ["g7g8"],
    rating: 894,
    hint: 'The rook delivers checkmate on g8 — the king protects it!',
    explanation: 'Rg8# — the rook delivers checkmate on g8. The king on h8 cannot escape: h7 is a pawn, the White king on f7 covers g8 and protects the rook.',
  },
  {
    id: 'i100',
    title: 'Queen g-file Checkmate',
    fen: '7k/5ppp/8/8/8/8/8/4Q2K w - - 0 1',
    solution: ["e1e8"],
    rating: 897,
    hint: 'The queen delivers checkmate from the 1st rank to the corner king!',
    explanation: 'Qe8# — the queen delivers checkmate on e8. The king on h8 cannot escape: f7, g7, h7 are pawns, and the queen covers the entire 8th rank.',
  },
];

export default puzzles;
