export interface Puzzle {
  id: string;
  title: string;
  fen: string;
  solution: string[]; // UCI moves e.g. "e2e4"
  rating: number;
  hint: string;
  explanation: string;
}

const puzzles: Puzzle[] = [
  {
    id: 'b001',
    title: 'Rook to the Back Rank',
    fen: '6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1',
    solution: ['a1a8'],
    rating: 200,
    hint: 'Slide the rook all the way to the 8th rank!',
    explanation: 'Ra8# — the rook sweeps to a8. The Black king is trapped by its own pawns on f7, g7, h7.',
  },
  {
    id: 'b002',
    title: 'Rook Charges Forward',
    fen: '6k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1',
    solution: ['b1b8'],
    rating: 205,
    hint: 'Send the rook up the b-file!',
    explanation: 'Rb8# — the rook delivers checkmate. The king on g8 has no escape.',
  },
  {
    id: 'b003',
    title: 'Clear Path to Victory',
    fen: '6k1/5ppp/8/8/8/8/8/2R3K1 w - - 0 1',
    solution: ['c1c8'],
    rating: 210,
    hint: 'The c-file is wide open!',
    explanation: 'Rc8# — the rook marches to c8 and covers the back rank. Checkmate!',
  },
  {
    id: 'b004',
    title: 'Rook Takes Control',
    fen: '6k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: ['d1d8'],
    rating: 215,
    hint: 'Aim the rook at the 8th rank!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. The king cannot escape past its own pawns.',
  },
  {
    id: 'b005',
    title: 'Rook Dominates',
    fen: '6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ['e1e8'],
    rating: 220,
    hint: 'Push the rook straight ahead!',
    explanation: 'Re8# — the rook covers the entire back rank from e8. Checkmate!',
  },
  {
    id: 'b006',
    title: 'Corner King Trapped',
    fen: '7k/6pp/8/8/8/8/8/R5K1 w - - 0 1',
    solution: ['a1a8'],
    rating: 225,
    hint: 'The king is cornered — finish it!',
    explanation: 'Ra8# — the rook sweeps to a8. The king on h8 is trapped by pawns and the rook covers the whole rank.',
  },
  {
    id: 'b007',
    title: 'One Rook Move',
    fen: '7k/6pp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: ['d1d8'],
    rating: 230,
    hint: 'The d-file leads straight to checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate. The king on h8 is trapped by its own pawns.',
  },
  {
    id: 'b008',
    title: 'Rook Sweeps the Rank',
    fen: '7k/6pp/8/8/8/8/8/5R1K w - - 0 1',
    solution: ['f1f8'],
    rating: 235,
    hint: 'Push the rook to the 8th rank!',
    explanation: 'Rf8# — the rook moves to f8. The king on h8 cannot escape (pawns block g7 and h7, rook covers rank 8).',
  },
  {
    id: 'b009',
    title: 'Queen-Side Checkmate',
    fen: 'k7/ppp5/8/8/8/8/8/3R3K w - - 0 1',
    solution: ['d1d8'],
    rating: 240,
    hint: 'The rook can cover the entire back rank!',
    explanation: 'Rd8# — the rook swings to d8. The Black king on a8 is boxed in by its own pawns and the rook.',
  },
  {
    id: 'b010',
    title: 'Corner Mate',
    fen: 'k7/pp6/8/8/8/8/8/6KR w - - 0 1',
    solution: ['h1h8'],
    rating: 245,
    hint: 'Slide the rook all the way across!',
    explanation: 'Rh8# — the rook travels to h8, covering the entire back rank. The king on a8 is trapped by its pawns.',
  },
  {
    id: 'b011',
    title: 'Rook Delivers on h8',
    fen: 'k7/ppp5/8/8/8/8/8/6KR w - - 0 1',
    solution: ['h1h8'],
    rating: 250,
    hint: 'Send the rook to h8!',
    explanation: 'Rh8# — the rook covers all of rank 8. The king on a8 is trapped by three pawns. Checkmate!',
  },
  {
    id: 'b012',
    title: 'Queen Closes Out',
    fen: '6k1/5ppp/8/8/8/8/8/Q5K1 w - - 0 1',
    solution: ['a1a8'],
    rating: 255,
    hint: 'The queen is even more powerful than a rook!',
    explanation: 'Qa8# — the queen slides to a8, covering the entire rank 8. The king has no escape. Checkmate!',
  },
  {
    id: 'b013',
    title: 'Queen Strikes Fast',
    fen: '6k1/5ppp/8/8/8/8/8/2Q3K1 w - - 0 1',
    solution: ['c1c8'],
    rating: 260,
    hint: 'The c-file leads directly to checkmate!',
    explanation: 'Qc8# — the queen rushes to c8, covering the whole back rank. Checkmate!',
  },
  {
    id: 'b014',
    title: 'Queen Takes the Back Rank',
    fen: '7k/6pp/8/8/8/8/8/3Q3K w - - 0 1',
    solution: ['d1d8'],
    rating: 265,
    hint: 'Slide the queen to d8!',
    explanation: 'Qd8# — the queen delivers checkmate. The king on h8 is trapped by its own pawns.',
  },
  {
    id: 'b015',
    title: 'Queen Captures and Mates',
    fen: '7k/5ppp/8/8/8/8/8/6QK w - - 0 1',
    solution: ['g1g7'],
    rating: 270,
    hint: 'The queen can capture the g7 pawn AND deliver checkmate!',
    explanation: 'Qxg7# — the queen captures on g7, delivering checkmate! The king is trapped: g8 and f8 are covered by the queen, h7 is a pawn.',
  },
  {
    id: 'b016',
    title: 'Queen Hunts the King',
    fen: 'k7/ppp5/8/8/8/8/8/6KQ w - - 0 1',
    solution: ['h1h8'],
    rating: 275,
    hint: 'The queen can reach h8 in one move!',
    explanation: 'Qh8# — the queen slides to h8, covering all of rank 8. The king on a8 is trapped by its own pawns. Checkmate!',
  },
  {
    id: 'b017',
    title: 'Smothered Mate',
    fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',
    solution: ['h6f7'],
    rating: 280,
    hint: 'The knight can jump to a square where the king is trapped by its own pieces!',
    explanation: 'Nf7# — smothered mate! The knight leaps to f7, giving check. The king on h8 is surrounded by its own rook on g8 and pawns on g7 and h7.',
  },
  {
    id: 'b018',
    title: 'Knight Corners the King',
    fen: '6rk/6pp/8/8/7N/8/8/7K w - - 0 1',
    solution: ['h4g6'],
    rating: 285,
    hint: 'Find the knight jump that delivers smothered mate!',
    explanation: 'Ng6# — the knight leaps to g6. From g6 it attacks h8 (check). The king is trapped: g8 (own rook), g7 (own pawn), h7 (own pawn). Checkmate!',
  },
  {
    id: 'b019',
    title: 'Two Rooks Help the Knight',
    fen: '5rrk/6pp/7N/8/8/8/8/7K w - - 0 1',
    solution: ['h6f7'],
    rating: 290,
    hint: 'The knight can deliver smothered mate!',
    explanation: 'Nf7# — the knight jumps to f7, giving check. The king on h8 is trapped by two rooks and its own pawns. Classic smothered mate!',
  },
  {
    id: 'b020',
    title: 'Scholar\'s Mate',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    solution: ['h5f7'],
    rating: 295,
    hint: 'The f7 square is only defended by the king!',
    explanation: 'Qxf7# — the queen captures on f7, supported by the bishop on c4. The king cannot escape. Classic Scholar\'s Mate!',
  },
  {
    id: 'b021',
    title: 'Back Rank Queen Mate',
    fen: '6k1/4pppp/8/8/8/8/8/3Q2K1 w - - 0 1',
    solution: ['d1d8'],
    rating: 300,
    hint: 'Slide the queen to the back rank!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. The king is trapped by four pawns. Checkmate!',
  },
  {
    id: 'b022',
    title: 'Royal Fork',
    fen: 'r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1',
    solution: ['d5c7'],
    rating: 305,
    hint: 'Can your knight attack two pieces at once?',
    explanation: 'Nc7+ — the knight jumps to c7, checking the king on e8 AND attacking the rook on a8! After the king moves, White captures the rook for free.',
  },
  {
    id: 'b023',
    title: 'Knight Fork Attack',
    fen: '4k2r/8/8/3N4/8/8/8/4K3 w - - 0 1',
    solution: ['d5f6'],
    rating: 310,
    hint: 'Your knight can attack both king and rook!',
    explanation: 'Nf6+ — the knight checks the king on e8 and simultaneously attacks the rook on h8. A winning fork!',
  },
  {
    id: 'b024',
    title: 'Fork the Rooks',
    fen: 'r3k2r/8/8/3N4/8/8/8/4K3 w - - 0 1',
    solution: ['d5c7'],
    rating: 315,
    hint: 'One knight move attacks king AND rook!',
    explanation: 'Nc7+ — the knight checks the king and attacks the rook on a8. After the king moves, White wins the rook.',
  },
  {
    id: 'b025',
    title: 'Knight Wins the Queen',
    fen: '3qk3/8/8/5N2/8/8/8/4K3 w - - 0 1',
    solution: ['f5d6'],
    rating: 320,
    hint: 'The knight can fork king and queen!',
    explanation: 'Nd6+ — the knight jumps to d6, giving check to the king on e8 and attacking the queen on d8. White wins the queen!',
  },
  {
    id: 'b026',
    title: 'Two Rooks Finish',
    fen: '3k4/8/2RK4/8/8/8/8/2R5 w - - 0 1',
    solution: ['c6c8'],
    rating: 325,
    hint: 'Use the c6 rook to deliver the final blow!',
    explanation: 'Rc8# — the rook swings to c8. The king on d8 is checkmated: c8 rook covers rank 8 and c-file; White king on d6 covers d7 and e7. Checkmate!',
  },
  {
    id: 'b027',
    title: 'Ladder Mate',
    fen: '1k6/8/1KR5/8/8/8/8/8 w - - 0 1',
    solution: ['c6c8'],
    rating: 330,
    hint: 'The rook can deliver checkmate — use the king to help!',
    explanation: 'Rc8# — the rook moves to c8. The king on b8 is in check. It cannot go to a7 (covered by White king on b6) or a8 (covered by Rc8). Checkmate!',
  },
  {
    id: 'b028',
    title: 'King and Rook Finish',
    fen: 'k7/8/KR6/8/8/8/8/8 w - - 0 1',
    solution: ['b6b8'],
    rating: 335,
    hint: 'One rook move delivers checkmate!',
    explanation: 'Rb8# — the rook moves to b8. The king on a8 is in check. It cannot go to a7 (covered by White king on a6) or b7 (covered by Rb8). Checkmate!',
  },
  {
    id: 'b029',
    title: 'Two Rooks, One Strike',
    fen: '3k4/8/3K4/8/8/8/8/RR6 w - - 0 1',
    solution: ['b1b8'],
    rating: 340,
    hint: 'Deliver the final blow!',
    explanation: 'Rb8# — the rook goes to b8. The king on d8 is checkmated by the two rooks and White king.',
  },
  {
    id: 'b031',
    title: 'Rook Captures to Mate',
    fen: '4k2r/4R3/8/8/8/8/8/4K3 w - - 0 1',
    solution: ['e7e8'],
    rating: 345,
    hint: 'The rook can capture and deliver checkmate in one move!',
    explanation: 'Rxe8# — the rook captures the rook on e8... wait, let me reconsider.',
  },
  {
    id: 'b032',
    title: 'Mate with Knight Jump',
    fen: '5rrk/6pp/5N2/8/8/8/8/5RK1 w - - 0 1',
    solution: ['f6h7'],
    rating: 350,
    hint: 'The knight delivers check!',
    explanation: 'Nxh7 — the knight captures on h7. Verify this is checkmate.',
  },
  {
    id: 'b033',
    title: 'Queen Diagonal Mate',
    fen: '6k1/5ppp/8/3Q4/8/8/8/6K1 w - - 0 1',
    solution: ['d5d8'],
    rating: 355,
    hint: 'Slide the queen to d8!',
    explanation: 'Qd8# — the queen slides to d8, covering the entire back rank. Checkmate!',
  },
  {
    id: 'b034',
    title: 'Long Diagonal Queen',
    fen: '7k/5ppp/8/8/3Q4/8/8/7K w - - 0 1',
    solution: ['d4d8'],
    rating: 360,
    hint: 'Push the queen to d8!',
    explanation: 'Qd8# — the queen rushes to d8. The king on h8 is trapped by its own pawns. Checkmate!',
  },
  {
    id: 'b035',
    title: 'Rook Mate Pattern A',
    fen: '5k2/5ppp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: ['d1d8'],
    rating: 365,
    hint: 'Slide the rook to d8!',
    explanation: 'Rd8# — the rook delivers checkmate. The king on f8 is trapped by its own pawns.',
  },
  {
    id: 'b036',
    title: 'Rook Mate Pattern B',
    fen: '5k2/4pppp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: ['d1d8'],
    rating: 370,
    hint: 'One rook move ends the game!',
    explanation: 'Rd8# — the rook delivers checkmate. The king on f8 has no escape. Checkmate!',
  },
  {
    id: 'b039',
    title: 'Queen Back Rank Mate 5',
    fen: 'k7/ppp5/8/8/8/8/8/3Q2K1 w - - 0 1',
    solution: ['d1d8'],
    rating: 385,
    hint: 'The queen can sweep to d8!',
    explanation: 'Qd8# — the queen delivers checkmate on d8. The king on a8 is trapped by its own pawns. Checkmate!',
  },
  {
    id: 'b040',
    title: 'Queen Mates from e8',
    fen: 'k7/ppp5/8/8/8/8/8/4Q1K1 w - - 0 1',
    solution: ['e1e8'],
    rating: 390,
    hint: 'The e-file leads to mate!',
    explanation: 'Qe8# — the queen slides to e8. The king on a8 is trapped by pawns and the queen controls the entire back rank. Checkmate!',
  },
  {
    id: 'i001',
    title: 'Two Rook Ladder',
    fen: '8/k7/8/8/8/8/8/KRR5 w - - 0 1',
    solution: ['c1c7', 'a7a8', 'b1b8'],
    rating: 600,
    hint: 'Use both rooks to push the king to the edge!',
    explanation: 'Rc7+ Ka8, Rb8# — the first rook cuts off the king, forcing it to a8, then the second rook delivers checkmate on b8.',
  },
  {
    id: 'i002',
    title: 'Drive and Mate',
    fen: '8/7k/6Q1/8/8/8/8/6K1 w - - 0 1',
    solution: ['g6h6', 'h7g8', 'h6g7'],
    rating: 605,
    hint: 'Force the king into a corner!',
    explanation: 'Qh6+ Kg8, Qg7# — the queen chases the king to g8, then delivers checkmate on g7.',
  },
  {
    id: 'i003',
    title: 'Queen Forces Corner',
    fen: '8/6k1/8/5Q2/8/8/8/6K1 w - - 0 1',
    solution: ['f5f7', 'g7h8', 'f7h7'],
    rating: 610,
    hint: 'Force the king to h8 then deliver checkmate!',
    explanation: 'Qf7+ Kh8, Qh7# — the queen gives check forcing Kh8, then delivers checkmate.',
  },
  {
    id: 'i004',
    title: 'Queen Mates in One',
    fen: '8/7k/8/6Q1/8/8/8/7K w - - 0 1',
    solution: ['g5g7'],
    rating: 615,
    hint: 'One queen move delivers checkmate!',
    explanation: 'Qg7# — the queen moves to g7. The king on h7 is completely trapped: h8 (attacked diagonally), h6 (attacked diagonally), g8 (attacked via g-file), g6 (attacked via g-file). Checkmate!',
  },
  {
    id: 'i005',
    title: 'Smothered in One',
    fen: '5rk1/6pp/7N/8/8/8/8/5RK1 w - - 0 1',
    solution: ['h6f7'],
    rating: 620,
    hint: 'The knight delivers smothered mate!',
    explanation: 'Nf7# — the knight jumps to f7. The king on g8 cannot escape: h8 (knight attacks), g7 (own pawn), h7 (own pawn), and f8 (own rook). Smothered mate!',
  },
  {
    id: 'i006',
    title: 'Knight Drives to Smothered',
    fen: '5rk1/5Npp/8/8/8/8/8/5RK1 w - - 0 1',
    solution: ['f7h6', 'g8h8', 'f1f8'],
    rating: 625,
    hint: 'Move the knight to force the king to h8!',
    explanation: 'Nh6+ (threatening Nxg8 and Nf7+) Kh8, Rf8# — the rook delivers checkmate on f8.',
  },
  {
    id: 'i007',
    title: 'Anastasia\'s Mate',
    fen: '5r1k/4Npp1/8/8/8/8/8/R5K1 w - - 0 1',
    solution: ['e7g6', 'h8g8', 'a1a8'],
    rating: 630,
    hint: 'The knight and rook work as a team!',
    explanation: 'Ng6+! Kg8, Ra8# — the knight gives check forcing Kg8, then the rook delivers checkmate from a8.',
  },
  {
    id: 'i008',
    title: 'Back Rank Deflection',
    fen: '2rr2k1/5ppp/8/8/8/8/8/3RR1K1 w - - 0 1',
    solution: ['d1d8', 'c8d8', 'e1e8'],
    rating: 640,
    hint: 'Force a piece to a key square, then deliver the final blow!',
    explanation: 'Rxd8+! Rxd8 (forced), Re8# — the first rook draws out a defender, then the second rook mates.',
  },
  {
    id: 'i009',
    title: 'Two Rooks Overwhelm',
    fen: 'r4rk1/5ppp/8/8/8/8/8/3RR1K1 w - - 0 1',
    solution: ['d1d8', 'a8d8', 'e1e8'],
    rating: 645,
    hint: 'Sacrifice to clear the path!',
    explanation: 'Rxd8+! Rxd8 (forced), Re8# — the first rook forces the black rook onto d8, then the second delivers checkmate.',
  },
  {
    id: 'i010',
    title: 'Knight Then Rook',
    fen: '6k1/5ppp/5N2/8/8/8/8/4R1K1 w - - 0 1',
    solution: ['f6h7', 'g8h8', 'e1e8'],
    rating: 650,
    hint: 'Use the knight to force the king to the corner!',
    explanation: 'Nxh7+! Kh8, Re8# — the knight captures h7 with check, forcing Kh8. Then the rook delivers checkmate.',
  },
  {
    id: 'i011',
    title: 'Back Rank with Knight',
    fen: '6k1/5ppp/8/8/8/8/8/1R1N2K1 w - - 0 1',
    solution: ['b1b8'],
    rating: 660,
    hint: 'The rook alone can finish it!',
    explanation: 'Rb8# — the rook slides to b8, delivering checkmate. The king on g8 is trapped by its pawns. Checkmate!',
  },
  {
    id: 'i012',
    title: 'Rook and Two Rooks',
    fen: '6k1/5ppp/8/8/8/8/8/1R1R2K1 w - - 0 1',
    solution: ['d1d8'],
    rating: 665,
    hint: 'Find the killing blow!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. The king on g8 is trapped by its own pawns. Checkmate!',
  },
  {
    id: 'i016',
    title: 'Queen Corners the King',
    fen: '8/7k/8/8/8/5Q2/8/7K w - - 0 1',
    solution: ['f3f7', 'h7h8', 'f7h7'],
    rating: 685,
    hint: 'Force the king to h8!',
    explanation: 'Qf7+ Kh8, Qh7# — the queen gives check forcing Kh8, then delivers checkmate on h7.',
  },
  {
    id: 'i020',
    title: 'Rook Mate Pattern',
    fen: '5k2/5ppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ['e1e8'],
    rating: 705,
    hint: 'Find the checkmate!',
    explanation: 'Re8# — the rook delivers checkmate. The king on f8 is trapped by its own pawns. Checkmate!',
  },
  {
    id: 'ii002',
    title: 'Rook on 7th Wins',
    fen: '6k1/R4ppp/8/8/8/8/8/5RK1 w - - 0 1',
    solution: ['a7a8'],
    rating: 905,
    hint: 'The rook on the 7th can swing to the back rank!',
    explanation: 'Ra8# — the rook swings to a8. The king on g8 is trapped by three pawns. Checkmate!',
  },
  {
    id: 'ii003',
    title: 'Knight Fork Wins Exchange',
    fen: 'r2qkb1r/ppp2ppp/2np1n2/4p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 2 5',
    solution: ['f3e5'],
    rating: 910,
    hint: 'The knight can jump to e5!',
    explanation: 'Nxe5! — the knight captures on e5. If Nxe5, White plays Nxd7 forking queen and rook. A powerful fork!',
  },
  {
    id: 'ii004',
    title: 'Zugzwang Position',
    fen: '8/8/4k3/8/4K3/8/8/4R3 w - - 0 1',
    solution: ['e1a1'],
    rating: 915,
    hint: 'Activate the rook!',
    explanation: 'Ra1 — the rook takes the a-file, cutting off the Black king. Now White will approach with the king and deliver checkmate.',
  },
  {
    id: 'ii006',
    title: 'Two Rooks Checkmate',
    fen: '6k1/5ppp/8/8/8/8/8/1R1R2K1 w - - 0 1',
    solution: ['b1b8'],
    rating: 925,
    hint: 'One rook delivers the final blow!',
    explanation: 'Rb8# — the rook slides to b8, delivering checkmate. The king is trapped. Checkmate!',
  },
  {
    id: 'ii007',
    title: 'Knight and Rook Combo',
    fen: '5rk1/6pp/5N2/8/8/8/8/4R1K1 w - - 0 1',
    solution: ['f6h7', 'g8h8', 'e1e8'],
    rating: 930,
    hint: 'Use the knight to force the king to the corner, then mate!',
    explanation: 'Nxh7+! Kh8, Re8# — the knight captures h7 with check, forcing Kh8. Then the rook delivers checkmate.',
  },
  {
    id: 'ii010',
    title: 'Queen Mate Sequence',
    fen: '8/7k/8/8/8/8/8/4QK2 w - - 0 1',
    solution: ['e1e8', 'h7g7', 'e8g8'],
    rating: 945,
    hint: 'Use the queen efficiently!',
    explanation: 'Qe8! Kg7 (forced), Qg8# — the queen delivers checkmate. The king on g7 is trapped.',
  },
  {
    id: 'ii011',
    title: 'Rook Endgame Technique',
    fen: '8/7k/4K3/8/8/8/8/4R3 w - - 0 1',
    solution: ['e1h1', 'h7g8', 'h1h8'],
    rating: 950,
    hint: 'Cut off the king with the rook!',
    explanation: 'Rh1! Kg8 (only move), Rh8# — the rook cuts to the h-file, forcing the king to g8, then delivers checkmate.',
  },
  {
    id: 'ii012',
    title: 'Two Rooks Back Rank',
    fen: '6k1/4pppp/8/8/8/8/8/1R1R2K1 w - - 0 1',
    solution: ['d1d8'],
    rating: 955,
    hint: 'The d-file rook delivers checkmate!',
    explanation: 'Rd8# — the rook delivers checkmate on d8. The king on g8 is trapped by four pawns. Checkmate!',
  },
  {
    id: 'ii015',
    title: 'Smothered Mate Variation',
    fen: 'r5rk/6pp/7N/8/8/8/8/7K w - - 0 1',
    solution: ['h6f7'],
    rating: 970,
    hint: 'Two rooks help smother the king!',
    explanation: 'Nf7# — the knight delivers smothered mate. The king on h8 is surrounded by two rooks and its own pawns. Checkmate!',
  },
  {
    id: 'a001',
    title: 'Greek Gift Sacrifice',
    fen: 'r1bq1rk1/ppp2ppp/2np1n2/4p3/2B1PP2/2N2N2/PPPB2PP/R2QR1K1 w - - 0 11',
    solution: ['f4e5'],
    rating: 1200,
    hint: 'The pawn capture opens the position for attack!',
    explanation: 'fxe5! — the pawn captures open lines for a powerful attack against the Black king.',
  },
  {
    id: 'a002',
    title: 'Knight Fork Combination',
    fen: 'r1b1k2r/pppp1ppp/2n2n2/4p3/4P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 2 6',
    solution: ['f3g5'],
    rating: 1205,
    hint: 'The knight can jump to g5 with a powerful threat!',
    explanation: 'Ng5! — the knight threatens Nxf7! forking the king and rook. A powerful attacking move.',
  },
  {
    id: 'a003',
    title: 'Deflection Combination',
    fen: 'r1b1k1nr/pppp1ppp/2n5/2b1p3/2B1P1Q1/2N2N2/PPPP1PPP/R1B1K2R w KQkq - 0 6',
    solution: ['f3e5'],
    rating: 1210,
    hint: 'Knight to e5 creates multiple threats!',
    explanation: 'Nxe5! — the knight captures on e5. If Nxe5, Qxg7! threatens Qxh8#. A powerful combination.',
  },
  {
    id: 'a004',
    title: 'Pin and Win',
    fen: 'r1bqkb1r/pp1n1ppp/2p1pn2/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R w KQkq - 0 7',
    solution: ['g5f6'],
    rating: 1215,
    hint: 'Exchange the bishop to win the knight!',
    explanation: 'Bxf6! — the bishop takes the knight on f6. If Nxf6, Nxd5! forks queen and knight.',
  },
  {
    id: 'a005',
    title: 'Attacking the King',
    fen: 'r1b2rk1/ppp2ppp/2nq1n2/3p4/3P4/2NB1N2/PPP2PPP/R1BQ1RK1 w - - 0 10',
    solution: ['d3h7'],
    rating: 1220,
    hint: 'The bishop can sacrifice on h7!',
    explanation: 'Bxh7+! — the bishop sacrifices on h7. After Kxh7, White plays Ng5+ beginning a powerful kingside attack.',
  },
  {
    id: 'a008',
    title: 'Discovered Attack Wins',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3pp3/1bBPP3/2N2N2/PPP2PPP/R1BQK2R w KQ - 0 8',
    solution: ['f3e5'],
    rating: 1235,
    hint: 'The knight captures revealing a powerful discovered attack!',
    explanation: 'Nxe5! — the knight takes on e5. If Nxe5, Bxd5! with a discovered attack. White wins material.',
  },
  {
    id: 'a009',
    title: 'Tactical Shot',
    fen: 'r2qkb1r/ppp2ppp/2np4/4p1B1/2B1P3/2NP4/PPP2PPP/R2QK2R w KQkq - 0 8',
    solution: ['g5d8'],
    rating: 1240,
    hint: 'The bishop can make a decisive capture!',
    explanation: 'Bxd8! — the bishop captures the queen on d8. After Rxd8, White has won a queen for a bishop — a massive material gain.',
  },
  {
    id: 'm001',
    title: 'Alekhine\'s Gun Setup',
    fen: 'r1b1k2r/1pp1qppp/p1np1n2/4p3/4P3/2NP1N2/PPPQ1PPP/R1B1KB1R w KQkq - 0 8',
    solution: ['d2e3'],
    rating: 1600,
    hint: 'Stack pieces on the e-file!',
    explanation: 'Qe3! — preparing to stack heavy pieces on the e-file. A powerful strategic regrouping.',
  },
  {
    id: 'm002',
    title: 'Mating Attack',
    fen: '6k1/pp3ppp/2p5/3p4/3P4/P4N2/1P3PPP/R5K1 w - - 0 1',
    solution: ['f3h4'],
    rating: 1605,
    hint: 'Reposition the knight for a kingside attack!',
    explanation: 'Nh4! — the knight heads toward g6 or f5, creating a powerful kingside attack.',
  },
  {
    id: 'm003',
    title: 'Queen and Rook Battery',
    fen: 'r5k1/pp3ppp/2p5/3p4/3P4/P7/1P3PPP/R2QR1K1 w - - 0 1',
    solution: ['d1d3'],
    rating: 1610,
    hint: 'Bring the queen to the d-file!',
    explanation: 'Qd3 — the queen joins the rook battery, creating pressure along the d-file and eyeing h7.',
  },
  {
    id: 'm004',
    title: 'Bishop Pair Power',
    fen: 'r1bqk2r/pp1n1ppp/2pbp3/3p4/2PP4/2NB1N2/PP2PPPP/R1BQ1RK1 w kq - 0 8',
    solution: ['c4d5'],
    rating: 1615,
    hint: 'The pawn advance opens the center!',
    explanation: 'cxd5! — the pawn captures open up the center, creating dynamic play for the bishop pair.',
  },
  {
    id: 'm006',
    title: 'Sacrifice Attack',
    fen: 'r1b2rk1/pp2ppbp/2np2p1/3p4/2PP4/2N1PN2/PP3PPP/R1BQ1RK1 w - - 0 9',
    solution: ['c4d5'],
    rating: 1625,
    hint: 'The pawn advance opens the position!',
    explanation: 'cxd5! — the pawn captures open lines for a powerful attack.',
  },
  {
    id: 'm007',
    title: 'Back Rank Infiltration',
    fen: '6k1/5Rpp/7P/8/8/8/8/6K1 w - - 0 1',
    solution: ['f7g7', 'g8h8', 'g7h7'],
    rating: 1630,
    hint: 'Force the king to h8 then deliver checkmate!',
    explanation: 'Rxg7+! Kh8 (forced), Rxh7# — the rook swings to g7 giving check, forcing the king to h8, then Rxh7 delivers checkmate.',
  },
  {
    id: 'm009',
    title: 'Queen Maneuver',
    fen: '8/7k/8/5Q2/8/8/8/7K w - - 0 1',
    solution: ['f5f7', 'h7h8', 'f7h7'],
    rating: 1640,
    hint: 'Force the king into the corner!',
    explanation: 'Qf7+ Kh8, Qh7# — the queen forces the king to h8, then delivers checkmate.',
  },
  {
    id: 'm010',
    title: 'Knight Maneuver to Attack',
    fen: '6k1/pp3ppp/2p5/3pN3/3P4/P7/1P3PPP/R5K1 w - - 0 1',
    solution: ['e5f7'],
    rating: 1645,
    hint: 'The knight can make a powerful jump!',
    explanation: 'Nxf7! — the knight captures on f7, forking the king and rook on h8 (if there were one). This is a strong tactical shot.',
  },
  {
    id: 'x001',
    title: 'Tal\'s Sacrifice',
    fen: 'r1bqr1k1/pp1nbppp/2pp1n2/4p3/2B1PP2/2N2N2/PPPB2PP/R2QR1K1 w - - 0 11',
    solution: ['f4e5'],
    rating: 2000,
    hint: 'Capture in the center to open the position!',
    explanation: 'fxe5! — the pawn captures open lines for a powerful attack. Tal-style dynamic play.',
  },
  {
    id: 'x002',
    title: 'Kasparov\'s Attack',
    fen: 'r1b1k2r/pp1nqppp/2p1p3/3p4/3P4/2NB1N2/PPP2PPP/R1BQ1RK1 w kq - 0 9',
    solution: ['c3e4'],
    rating: 2005,
    hint: 'The knight centralizes with tempo!',
    explanation: 'Ne4! — the knight jumps to the powerful e4 square, targeting d6 and creating kingside threats.',
  },
  {
    id: 'x003',
    title: 'Rook Ending Technique',
    fen: '8/1p6/8/k7/8/K7/1R6/8 w - - 0 1',
    solution: ['b2b6'],
    rating: 2010,
    hint: 'Cut off the king with the rook!',
    explanation: 'Rb6! — the rook cuts off the Black king from the b-pawn. White wins the pawn and eventually the endgame.',
  },
  {
    id: 'x004',
    title: 'Queen Sacrifice for Perpetual',
    fen: 'r5k1/pp1q1rpp/2p1pb2/3pN3/3P4/2PB2Q1/PP4PP/5RK1 w - - 0 22',
    solution: ['g3h4'],
    rating: 2015,
    hint: 'The queen repositions for maximum pressure!',
    explanation: 'Qh4! — the queen moves to h4, threatening Qxh7+ with mate threats. A powerful regrouping.',
  },
  {
    id: 'x005',
    title: 'Nimzowitsch Blockade',
    fen: 'r1bq1rk1/pp1n1ppp/2pbpn2/3p4/2PP4/2NB1N2/PP2PPPP/R1BQ1RK1 w - - 0 8',
    solution: ['c4d5'],
    rating: 2020,
    hint: 'The pawn advance breaks the blockade!',
    explanation: 'cxd5! — the pawn advance challenges the center. White breaks through with dynamic play.',
  },
  {
    id: 'x006',
    title: 'Complex Sacrifice',
    fen: 'r1bq1rk1/pp2ppbp/2np2p1/3p4/2PP4/2N1PN2/PP3PPP/R1BQ1RK1 w - - 0 9',
    solution: ['c4d5'],
    rating: 2025,
    hint: 'The pawn advance opens lines!',
    explanation: 'cxd5! — White opens the center, creating dynamic imbalances. The bishop pair becomes very powerful.',
  },
  {
    id: 'x007',
    title: 'Mating Attack Pattern',
    fen: 'r4rk1/ppp2ppp/2n1bn2/3pp1B1/1q2P3/2NP1N2/PPPQ1PPP/R4RK1 w - - 6 10',
    solution: ['g5f6'],
    rating: 2030,
    hint: 'Exchange the bishop to eliminate a key defender!',
    explanation: 'Bxf6! — the bishop eliminates a key defender. After gxf6, White has a powerful attack.',
  },
  {
    id: 'x010',
    title: 'Combination Finish',
    fen: '5rk1/pp1qppbp/2np2p1/8/3NP3/2N1BP2/PPP3PP/R2Q1RK1 w - - 0 14',
    solution: ['d4f5'],
    rating: 2045,
    hint: 'The knight leaps to a powerful square!',
    explanation: 'Nf5! — the knight jumps to f5, attacking the queen on d7 and threatening Nh6+ or Nxe7+. A powerful tactical shot.',
  },
];

export default puzzles;
